import {assertBidCapacity} from './solvency';
import {teamNews} from './newsStatistics';
import {Express} from 'express';import {db} from '../db';import {clubs,players,gameRecords,worldState} from '../db/schema';import {eq,sql} from 'drizzle-orm';import {put,record,records} from './records';import {ARTIFACTS} from '../constants/market';import {randomUUID} from 'node:crypto';
async function lock(id:string,tx:any){const [r]=await tx.select().from(gameRecords).where(eq(gameRecords.id,id)).for('update');return r?{id:r.id,...r.payload}:null;}
export async function initializeArtifactMarket(){if(await record('artifact-auctions-v2'))return;await db.transaction(async(tx:any)=>{
 if(await record('artifact-auctions-v2',tx))return; const upgraded=await record('artifact-auctions-v1',tx);
 for(const a of ARTIFACTS.filter(a=>!['falcon-ring','silk-wraps'].includes(a.id)).filter(a=>!upgraded||!['speed-boots','mithril','keeper-gloves','seven-mile-boots'].includes(a.id)))for(let n=0;n<a.supply;n++){const itemId='item-'+randomUUID();await put('artifact-item',itemId,{artifactId:a.id,clubId:null,playerId:null,listed:true},tx);await put('artifact-auction','artifact-auction-'+randomUUID(),{itemId,artifactId:a.id,sellerId:null,price:a.price,bidderId:null,endsAt:new Date(Date.now()+7*86400000).toISOString(),closed:false},tx);}
 if(!upgraded)for(const p of await tx.select().from(players))for(const id of p.artifacts||[])if(ARTIFACTS.some(a=>a.id===id))await put('artifact-item','legacy-item-'+p.id+'-'+id,{artifactId:id,clubId:p.clubId,playerId:p.id,listed:false},tx);
 await put('system','artifact-auctions-v2',{date:new Date().toISOString()},tx);
});}
export async function finishArtifactAuction(id:string,date:string){await db.transaction(async(tx:any)=>{const a=await lock(id,tx);if(!a||a.closed||+new Date(a.endsAt)>+new Date(date))return;const item=await lock(a.itemId,tx);if(a.bidderId){if(a.unreserved)await tx.update(clubs).set({gold:sql`${clubs.gold}-${a.price}`}).where(eq(clubs.id,a.bidderId));await put('artifact-item',item.id,{...item,clubId:a.bidderId,playerId:null,listed:false,...(item.artifactId==='moon-staff'?{expiresSeason:item.expiresSeason??(await tx.select().from(worldState))[0].season}:{})},tx);if(a.sellerId){await tx.update(clubs).set({gold:sql`${clubs.gold}+${a.price}`}).where(eq(clubs.id,a.sellerId));await put('ledger','artifact-sale-'+a.id,{clubId:a.sellerId,category:'Artefaktförsäljning',amount:a.price,date},tx);}await put('ledger','artifact-purchase-'+a.id,{clubId:a.bidderId,category:'Artefaktköp',amount:-a.price,date},tx);}else await put('artifact-item',item.id,{...item,listed:false},tx);await put('artifact-auction',a.id,{...a,closed:true},tx);});}
export function registerArtifactMarket(app:Express){const route=(method:'get'|'post',path:string,fn:(req:any)=>Promise<any>)=>app[method](path,async(req,res)=>{try{res.json(await fn(req));}catch(e:any){res.status(400).json({error:e.message});}});
 route('get','/api/artifact-market/:clubId',async req=>{const all=await db.select().from(clubs),ps=await db.select().from(players);const auctions=await records('artifact-auction'),season=(await db.select().from(worldState))[0].season;return {season,auctions:auctions.filter(a=>!a.closed).map(a=>({...a,artifact:ARTIFACTS.find(x=>x.id===a.artifactId),bidderName:all.find(c=>c.id===a.bidderId)?.name||'Inga bud',sellerName:all.find(c=>c.id===a.sellerId)?.name||'Kejsardömets marknad'})),inventory:(await records('artifact-item')).filter(i=>i.clubId===req.params.clubId).map(i=>({...i,artifact:ARTIFACTS.find(a=>a.id===i.artifactId),playerName:ps.find(p=>p.id===i.playerId)?.name})),bids:(await records('artifact-bid')).filter(b=>b.clubId===req.params.clubId).sort((a,b)=>b.amount-a.amount||b.date.localeCompare(a.date)).filter((b,i,all)=>all.findIndex(x=>x.auctionId===b.auctionId)===i).map(b=>{const a=auctions.find(a=>a.id===b.auctionId);return {...b,highestBid:a?.price,bidderName:all.find(c=>c.id===a?.bidderId)?.name||'Inga bud',name:ARTIFACTS.find(x=>x.id===a?.artifactId)?.name,status:a?.bidderId===b.clubId&&a.price===b.amount?(a.closed?'Vunnet':'Ledande'):a?.closed?'Avslutat':'Överbjudet'};})};});
 route('post','/api/artifact-bid/:id',async req=>db.transaction(async(tx:any)=>{const a=await lock(req.params.id,tx);if(!a||a.closed||+new Date(a.endsAt)<=Date.now())throw Error('Budgivningen är avslutad.');const [club]=await tx.select().from(clubs).where(eq(clubs.id,req.body.clubId)).for('update');if(!club||club.isBot||a.sellerId===club.id)throw Error('Ogiltig budgivare.');const offeredItem=await record(a.itemId,tx);if(offeredItem?.artifactId==='moon-staff'&&offeredItem.expiresSeason!==undefined&&offeredItem.expiresSeason<(await tx.select().from(worldState))[0].season)throw Error('Stavens kraft är uttömd.');const amount=Number(req.body.amount),minimum=a.bidderId?Math.ceil(a.price*1.03):a.price;if(!Number.isInteger(amount)||amount<minimum)throw Error('Minsta bud är '+minimum+' guld.');await assertBidCapacity(tx,club,amount,a.id);const endsAt=+new Date(a.endsAt)-Date.now()<600000?new Date(+new Date(a.endsAt)+60000).toISOString():a.endsAt;await put('artifact-auction',a.id,{...a,bidderId:club.id,price:amount,endsAt,unreserved:true},tx);if(a.bidderId&&a.bidderId!==club.id)await teamNews(tx,a.bidderId,a.id+'-'+amount,'Du har blivit överbjuden','Budet på artefakten är nu '+amount+' guld. Inga pengar har dragits för ditt bud.');if(a.sellerId)await teamNews(tx,a.sellerId,a.id+'-'+amount,'Din artefakt har fått ett bud','Högsta budet är '+amount+' guld.');await put('artifact-bid','artifact-bid-'+randomUUID(),{auctionId:a.id,clubId:club.id,amount,date:new Date().toISOString()},tx);return {success:true};}));
 route('post','/api/artifact-equip/:id',async req=>db.transaction(async(tx:any)=>{const item=await lock(req.params.id,tx);if(!item||item.clubId!==req.body.clubId||item.listed)throw Error('Artefakten kan inte utrustas.');if(item.playerId)throw Error('Artefakten är bunden till sin bärare och kan inte tas av.');if(item.artifactId==='moon-staff')throw Error('Staven verkar från klubbens förråd och bärs inte av en spelare.');if(['herbal-brew','black-brew','dragon-blood'].includes(item.artifactId)){
 const [p]=await tx.select().from(players).where(eq(players.id,Number(req.body.playerId))).for('update');if(!p||p.clubId!==item.clubId||p.isDeceased||p.isMercenary)throw Error('Välj en egen levande spelare.');
 const changes:any={};if(item.artifactId==='herbal-brew'){if(p.currentInjury<=0)throw Error('Spelaren är redan skadefri.');changes.currentInjury=Math.max(0,p.currentInjury-2.5)}
 if(item.artifactId==='black-brew'){if(p.form>=16)throw Error('Spelaren har redan högsta form.');changes.form=Math.min(16,p.form+3)}
 if(item.artifactId==='dragon-blood'){if(p.artifacts.some((a:string)=>a.startsWith('effect:dragon-blood:')&&Number(a.split(':')[2])>Date.now()))throw Error('Drakblod verkar redan på spelaren.');if(p.totalInjury+.5>=9)throw Error('Spelaren skulle inte överleva brygden.');changes.totalInjury=p.totalInjury+.5;changes.artifacts=[...p.artifacts,'effect:dragon-blood:'+(Date.now()+8*86400000)];}
 await tx.update(players).set(changes).where(eq(players.id,p.id));await put('artifact-item',item.id,{...item,clubId:null,consumedBy:p.id,consumedAt:new Date().toISOString(),listed:false},tx);return {success:true};
 }if(item.playerId){const [old]=await tx.select().from(players).where(eq(players.id,item.playerId));await tx.update(players).set({artifacts:old.artifacts.filter((id:string)=>id!==item.artifactId)}).where(eq(players.id,old.id));}const playerId=req.body.playerId?Number(req.body.playerId):null;if(!playerId)throw Error('Välj en spelare som ska bära artefakten.');if(playerId){const [p]=await tx.select().from(players).where(eq(players.id,playerId));if(!p||p.clubId!==item.clubId||p.isDeceased||p.isMercenary||p.artifacts.includes(item.artifactId))throw Error('Välj en egen spelare utan samma artefakt.');await tx.update(players).set({artifacts:[...p.artifacts,item.artifactId]}).where(eq(players.id,p.id));}await put('artifact-item',item.id,{...item,playerId},tx);return {success:true};}));
 route('post','/api/artifact-list/:id',async req=>db.transaction(async(tx:any)=>{const item=await lock(req.params.id,tx),price=Number(req.body.price);if(!item||item.clubId!==req.body.clubId||item.listed||item.playerId)throw Error('Bara obundna artefakter i förrådet kan säljas.');if(item.artifactId==='moon-staff'&&item.expiresSeason<(await tx.select().from(worldState))[0].season)throw Error('Stavens kraft är uttömd.');if(!Number.isInteger(price)||price<1)throw Error('Ange ett giltigt utgångspris.');await put('artifact-item',item.id,{...item,listed:true},tx);await put('artifact-auction','artifact-auction-'+randomUUID(),{itemId:item.id,artifactId:item.artifactId,sellerId:item.clubId,price,bidderId:null,endsAt:new Date(Date.now()+7*86400000).toISOString(),closed:false},tx);return {success:true};}));
}
