import {sql} from 'drizzle-orm';
import {Express} from 'express';import {randomBytes,scryptSync,timingSafeEqual,createHash,randomUUID} from 'node:crypto';import {db} from '../db';import {clubs} from '../db/schema';import {records,record,put} from './records';
const digest=(s:string)=>createHash('sha256').update(s).digest('hex');
export function registerAuth(app:Express){
 const attempts=new Map<string,{count:number;at:number}>();
 const token=(req:any)=>String(req.headers.cookie||'').split(';').map((s:string)=>s.trim()).find((s:string)=>s.startsWith('arena_session='))?.slice(14)||'';
 const current=async(req:any)=>{const s=await record('session-'+digest(token(req)));return s&&s.expires>Date.now()?s:null};
 const local=(req:any)=>['127.0.0.1','::1','::ffff:127.0.0.1'].includes(req.socket.remoteAddress)&&!process.env.PUBLIC_ORIGIN;
 const cookie=(value:string,age:number)=>'arena_session='+value+'; HttpOnly; SameSite=Strict; Path=/; Max-Age='+age+(process.env.PUBLIC_ORIGIN?.startsWith('https:')?'; Secure':'');
 app.get('/api/auth/status',async(req,res)=>{const session=await current(req);const accounts=await records('account');const existing=(await db.select().from(clubs)).find(c=>!c.isBot);res.json({serverTime:Date.now(),user:session?{userId:session.userId,name:session.name,guest:!!session.guest}:null,setup:!accounts.length&&local(req),registration:process.env.PUBLIC_ORIGIN?process.env.ALLOW_SIGNUPS==='true':accounts.length>0,setupName:!accounts.length&&local(req)?existing?.ownerName:undefined});});
 app.post('/api/auth/login',async(req,res)=>{try{const key=req.ip||'local',now=Date.now();let a=attempts.get(key);if(!a||now-a.at>600000){a={count:0,at:now};attempts.set(key,a)}if(++a.count>15)return res.status(429).json({error:'För många försök. Vänta en stund.'});const name=String(req.body.name||'').trim(),password=String(req.body.password||'');if(password.length<10||password.length>128||name.length<2||name.length>50)throw Error('Ange ett namn och ett lösenord med 10–128 tecken.');let account=(await records('account')).find(a=>a.name.toLowerCase()===name.toLowerCase());if(req.body.setup||req.body.register){account=await db.transaction(async(tx:any)=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(719044)`);const accounts=await records('account',tx),teams=await tx.select().from(clubs);if(req.body.setup){if(accounts.length||!local(req))throw Error('Kontot är redan konfigurerat.');const existing=teams.find((c:any)=>!c.isBot);if(existing&&existing.ownerName!==name)throw Error('Använd ditt befintliga managernamn.');}else{if(process.env.PUBLIC_ORIGIN?process.env.ALLOW_SIGNUPS!=='true':!accounts.length)throw Error('Registreringen är inte öppen.');if(accounts.some(a=>a.name.toLowerCase()===name.toLowerCase())||teams.some((c:any)=>!c.isBot&&c.ownerName.toLowerCase()===name.toLowerCase()))throw Error('Namnet är upptaget.');}const existing=req.body.setup?teams.find((c:any)=>!c.isBot):null,salt=randomBytes(16).toString('hex');const created={name,userId:existing?.userId||'usr_'+randomUUID(),salt,hash:scryptSync(password,salt,64).toString('hex')};await put('account','account-'+digest(name.toLowerCase()),created,tx);return created;});}if(!account||!timingSafeEqual(scryptSync(password,account.salt,64),Buffer.from(account.hash,'hex')))throw Error('Fel namn eller lösenord.');const t=randomBytes(32).toString('hex');await put('session','session-'+digest(t),{userId:account.userId,name:account.name,expires:now+7*86400000});attempts.delete(key);res.setHeader('Set-Cookie',cookie(t,604800));res.json({userId:account.userId,name:account.name});}catch(e:any){res.status(400).json({error:e.message})}});
 app.post('/api/auth/guest',async(req,res)=>{const t=randomBytes(32).toString('hex');await put('session','session-'+digest(t),{userId:'guest',name:'Gäst',guest:true,expires:Date.now()+86400000});res.setHeader('Set-Cookie',cookie(t,86400));res.json({userId:'guest',name:'Gäst',guest:true})});
 app.post('/api/auth/logout',async(req,res)=>{await put('session','session-'+digest(token(req)),{expires:0});res.setHeader('Set-Cookie',cookie('',0));res.json({success:true});});
 app.use('/api',async(req:any,res,next)=>{try{if(req.path==='/health')return next();const session=await current(req);if(!session)return res.status(401).json({error:'Logga in för att fortsätta.'});req.arenaUser=session;
 if(session.guest){const allowed=/^\/(world|series|divisions|places|place|statistics|club-detail|club-statistics|club-player-statistics|club-extras|club-transfers|player-detail|player-history|player-statistics|entity-index|venues|venue|fixtures|match|imperial-games|imperial-honours|guestbook|forum|forum-thread)(\/|$)/.test(req.path);if(req.method!=='GET'||!allowed)return res.status(403).json({error:'Gästläget är för att läsa spelvärlden. Logga in med ett managerkonto för att spela.'});req.query.viewerUserId='guest';return next();}
 
 if(req.method!=='GET'){const origin=req.headers.origin;if(origin&&origin!==process.env.PUBLIC_ORIGIN&&origin!=='http://'+req.headers.host)return res.status(403).json({error:'Ogiltigt ursprung.'});if(req.path.startsWith('/admin/')||['/matches/simulate-round','/tipset','/imperial-games/test'].includes(req.path))return res.status(403).json({error:'Administrationsåtgärden är inte tillgänglig här.'});}
 const own=(await db.select().from(clubs)).find(c=>c.userId===session.userId);const routeClub=req.path.match(/^\/(?:clubs|economy|bids|scout|scout-routes|magic-state|magic-cast|magic|lineup-presets|training-gains|artifact-market|tips|loans|club-settings)\/([^/]+)/)?.[1];const asserted=req.body?.clubId||req.query.clubId||(routeClub==='create'?null:routeClub);
 if(asserted&&asserted!==own?.id)return res.status(403).json({error:'Du kan bara ändra eller planera för ditt eget lag.'});if(req.path.startsWith('/user/')&&decodeURIComponent(req.path.split('/')[2])!==session.userId)return res.status(403).json({error:'Kontot tillhör en annan manager.'});req.query.viewerUserId=session.userId;if(req.body?.userId)req.body.userId=session.userId;if(req.body?.managerName)req.body.managerName=session.name;next();}catch{res.status(500).json({error:'Kunde inte kontrollera sessionen.'})}});
 app.post('/api/auth/password',async(req:any,res)=>{try{const now=Date.now(),key='password-'+req.arenaUser.userId;let attempt=attempts.get(key);if(!attempt||now-attempt.at>600000){attempt={count:0,at:now};attempts.set(key,attempt)}if(++attempt.count>10)throw Error('För många försök. Vänta en stund.');const password=String(req.body.password||''),old=String(req.body.oldPassword||'');if(password.length<10||password.length>128||old.length>128)throw Error('Välj ett lösenord med 10–128 tecken.');await db.transaction(async(tx:any)=>{const a=(await records('account',tx)).find(a=>a.userId===req.arenaUser.userId);if(!a||!timingSafeEqual(scryptSync(old,a.salt,64),Buffer.from(a.hash,'hex')))throw Error('Det nuvarande lösenordet stämmer inte.');const salt=randomBytes(16).toString('hex');await put('account',a.id,{...a,salt,hash:scryptSync(password,salt,64).toString('hex')},tx);for(const session of (await records('session',tx)).filter(s=>s.userId===a.userId))await put('session',session.id,{expires:0},tx);});res.setHeader('Set-Cookie',cookie('',0));res.json({success:true});}catch(e:any){res.status(400).json({error:e.message})}});

}
