import {or as eitherClub} from 'drizzle-orm';
import {clubMorale} from './revision13';
import {marketProfile,mercenaryFee} from '../engine/marketProfiles';
import {generatePlayerName} from '../engine/names';
import {initializeArtifactMarket} from './artifactMarket';
import {SeededRNG} from '../engine/matchEngine';
import {Express} from 'express';
import {db} from '../db';import {clubs,players,matches,worldState} from '../db/schema';import {eq,sql} from 'drizzle-orm';
import {record,records,put} from './records';import {PLACES,nearbyPlaces} from '../constants/geography';import {ARTIFACTS,COACHES} from '../constants/market';
import {generateSinglePlayer,calculateWage} from '../engine/playerGenerator';import {randomUUID} from 'node:crypto';
function visible(p:any,reveal=false){const {attributes,...rest}=p;return {...rest,...((p.isMercenary||reveal)?{attributes:Object.fromEntries(Object.entries(attributes).map(([k,v])=>[k,Math.round(Number(v)*1000)/1000]))}:{})};}
export async function initializeFeatures(){
 if(!await record('recruitment-v4'))await db.transaction(async(tx:any)=>{
  if(await record('recruitment-v4',tx))return;
  const existing=(await tx.select().from(players)).filter((p:any)=>p.isMercenary).length;
  const races=['human','elf','dwarf','orc','goblin','troll'] as const;
  for(let i=existing;i<144;i++){const race=races[i%6],home=PLACES.find(p=>p.race===race)!;const p=generateSinglePlayer(0,race,'',home.name,1);const rng=new SeededRNG(i*157+731),tier=Math.floor(i/6)%4;
   for(const key of Object.keys(p.attributes) as Array<keyof typeof p.attributes>)p.attributes[key]=Math.round(([1,4,8,12][tier]+rng.next()*3.5)*100)/100;
   const primary=['malvakt','markering','passning','snabbhet','skott','tuffhet'][Math.floor(i/24)%6] as keyof typeof p.attributes;p.attributes[primary]+=2;
   p.wage=calculateWage(p.attributes);p.nominalPosition=primary==='malvakt'?'Målvakt':'Fribrytare';
   const {id,positionRatingsWithForm,positionRatingsWithoutForm,...row}=p;await tx.insert(players).values({...row,clubId:null,isMercenary:true});
  }
  await put('system','recruitment-v4',{date:new Date().toISOString()},tx);
 });
 if(!await record('recruitment-v5'))await db.transaction(async(tx:any)=>{
  const all=await tx.select().from(players),free=all.filter((p:any)=>p.isMercenary&&!p.clubId).sort((a:any,b:any)=>a.id-b.id);
  for(let i=0;i<free.length;i++){const p=free[i],attributes=marketProfile(i,true);await tx.update(players).set({attributes,wage:calculateWage(attributes),nominalPosition:i%6===0?'Målvakt':'Fribrytare',name:generatePlayerName(p.race)}).where(eq(players.id,p.id));}
  const auctions=(await records('auction',tx)).filter(a=>!a.closed&&!a.sellerId&&!a.bidderId);let n=0;for(const auction of auctions){const p=all.find((p:any)=>p.id===auction.playerId);if(!p||p.clubId)continue;const attributes=marketProfile(n++,false);await tx.update(players).set({attributes,wage:calculateWage(attributes),name:generatePlayerName(p.race)}).where(eq(players.id,p.id));}
  // Preserve human rosters and names; remove duplicated generated bot names.
  const teams=await tx.select().from(clubs),botIds=new Set(teams.filter((c:any)=>c.isBot).map((c:any)=>c.id)),seen=new Set<string>();
  for(const p of all){if(seen.has(p.name)&&botIds.has(p.clubId)){let name;do{name=generatePlayerName(p.race)}while(seen.has(name));await tx.update(players).set({name}).where(eq(players.id,p.id));seen.add(name)}else seen.add(p.name);}
  for(const c of teams)if(c.coach){const coach=COACHES.find(x=>x.id===c.coach.id);if(coach)await tx.update(clubs).set({coach}).where(eq(clubs.id,c.id));}
  await put('system','recruitment-v5',{date:new Date().toISOString()},tx);
 });
 if(!await record('balance-v6'))await db.transaction(async(tx:any)=>{
  const all=await tx.select().from(players),seen=new Set(all.filter((p:any)=>p.clubId&&!p.name.includes(' ')).map((p:any)=>p.name));let n=0;
  for(const p of all){const change:any={};if(p.isMercenary&&!p.clubId){const index=n++;change.attributes=marketProfile(index,true);change.nominalPosition=['Målvakt','Back','Innermittfält','Yttermittfält','Anfall','Back'][(Math.floor(index/6)+index)%6];const homes=PLACES.filter(x=>x.race===p.race);change.hometown=homes[Math.floor(index/6)%homes.length].name;}
   change.wage=calculateWage(change.attributes||p.attributes);
   if(p.name.includes(' ')){let name;do{name=generatePlayerName(p.race)}while(seen.has(name));change.name=name;seen.add(name)}
   await tx.update(players).set(change).where(eq(players.id,p.id));
  }for(const a of (await records('artifact-auction',tx)).filter(a=>!a.closed&&['falcon-ring','silk-wraps'].includes(a.artifactId))){if(a.bidderId)await tx.update(clubs).set({gold:sql`${clubs.gold}+${a.price}`}).where(eq(clubs.id,a.bidderId));await put('artifact-auction',a.id,{...a,closed:true,cancelled:true},tx);const item=await record(a.itemId,tx);if(item)await put('artifact-item',item.id,{...item,listed:false,retired:true},tx);}
  await put('system','balance-v6',{date:new Date().toISOString()},tx);
 });
 if(!await record('precision-v7'))await db.transaction(async(tx:any)=>{const all=await tx.select().from(players);for(const p of all){const rng=new SeededRNG(p.id*271+977);const attributes=Object.fromEntries(Object.entries(p.attributes).map(([k,v])=>[k,Math.round((Number(v)+rng.next()*.008+.001)*1000)/1000]));await tx.update(players).set({attributes}).where(eq(players.id,p.id));}await put('system','precision-v7',{date:new Date().toISOString()},tx);});
 await initializeArtifactMarket();
}
export function registerFeatures(app:Express){
 const route=(method:'get'|'post',path:string,fn:(req:any)=>Promise<any>)=>app[method](path,async(req,res)=>{try{res.json(await fn(req));}catch(e:any){res.status(400).json({error:e.message});}});
 route('get','/api/search',async req=>{
  const q=String(req.query.q||'').trim().toLocaleLowerCase('sv'),all=await db.select().from(clubs),ps=await db.select().from(players);
  const min=(key:string,fallback:number)=>req.query[key]!==undefined&&req.query[key]!==''?Number(req.query[key]):fallback;
  const wageMin=min('wageMin',0),wageMax=min('wageMax',Infinity),levelMin=min('levelMin',0),levelMax=min('levelMax',Infinity);
  if([wageMin,wageMax,levelMin,levelMax].some(n=>Number.isNaN(n))||wageMin>wageMax||levelMin>levelMax)throw Error('Kontrollera intervallen.');
  const transferIds=new Set((await records('auction')).filter(a=>!a.closed&&+new Date(a.endsAt)>Date.now()).map(a=>a.playerId));const ownedIds=new Set(all.filter(c=>req.query.viewerUserId&&c.userId===req.query.viewerUserId).map(c=>c.id));const canView=(p:any)=>p.isMercenary||transferIds.has(p.id)||ownedIds.has(p.clubId);
  const home=String(req.query.hometown||''),race=String(req.query.race||''),attr=String(req.query.attribute||'');
  const hit=(s:string)=>s.toLocaleLowerCase('sv').includes(q),allowed=(p:any)=>(!home||p.hometown===home)&&(!race||p.race===race);
  const filtered=ps.filter(p=>(!q||hit(p.name)||String(p.id)===q)&&allowed(p)&&p.wage>=wageMin&&p.wage<=wageMax&&(!attr||(canView(p)&&attr in (p.attributes as any)&&(p.attributes as any)[attr]>=levelMin&&(p.attributes as any)[attr]<=levelMax)));
  const sortKey=['name','clubName','hometown','wage'].includes(String(req.query.sort))?String(req.query.sort):'name',direction=req.query.direction==='-1'?-1:1;const order=(a:any,b:any)=>direction*(sortKey==='wage'?(a.wage||0)-(b.wage||0):String(sortKey==='clubName'?(a.clubName||a.division||all.find(c=>c.id===a.clubId)?.name||''):a[sortKey]||'').localeCompare(String(sortKey==='clubName'?(b.clubName||b.division||all.find(c=>c.id===b.clubId)?.name||''):b[sortKey]||''),'sv'));filtered.sort(order);
  return {players:filtered.slice(0,150).map(p=>({...visible(p,canView(p)),clubName:all.find(c=>c.id===p.clubId)?.name||'Inget lag'})),clubs:all.filter(c=>hit(c.name)&&allowed(c)).sort(order).slice(0,100).map(c=>({id:c.id,name:c.name,division:c.division,race:c.race,hometown:c.hometown})),managers:all.filter(c=>!c.isBot&&hit(c.ownerName)&&allowed(c)).map(c=>({id:c.id,name:c.ownerName,clubName:c.name,hometown:c.hometown})).sort(order).slice(0,100),playerCount:filtered.length};
 });
 route('get','/api/player-detail/:id',async req=>{const [p]=await db.select().from(players).where(eq(players.id,Number(req.params.id)));if(!p)throw Error('Spelaren saknas.');const [c]=p.clubId?await db.select().from(clubs).where(eq(clubs.id,p.clubId)):[];const awaitAuction=(await records('auction')).find(a=>a.playerId===p.id&&!a.closed);const listed=(await records('auction')).some(a=>a.playerId===p.id&&!a.closed&&+new Date(a.endsAt)>Date.now());return {...visible(p,p.isMercenary||listed||!!(req.query.viewerUserId&&c?.userId===req.query.viewerUserId)),bidderName:(await db.select().from(clubs)).find(t=>t.id===(awaitAuction?.bidderId))?.name,clubName:c?.name||'Inget lag',owned:c?.userId===req.arenaUser.userId,listed,auction:(await records('auction')).find(a=>a.playerId===p.id&&!a.closed&&+new Date(a.endsAt)>Date.now())||null};});
 route('get','/api/club-detail/:id',async req=>{const [c]=await db.select().from(clubs).where(eq(clubs.id,req.params.id));if(!c)throw Error('Laget saknas.');const {id,name,shortName,race,hometown,division,position,merit,marathonPoints,wins,draws,losses,goalsFor,goalsAgainst,recordString,presentation,ownerName,isBot,arena,coach}=c;const publicClub={id,name,shortName,race,hometown,division,position,merit,marathonPoints,wins,draws,losses,goalsFor,goalsAgainst,recordString,presentation,ownerName,isBot,arena:arena?{name:(arena as any).name,capacity:(arena as any).capacity}:null,coach:coach?{name:(coach as any).name}:null};const squad=await db.select().from(players).where(eq(players.clubId,c.id));return {...publicClub,bankruptcy:await record('bankruptcy-'+c.id),morale:Math.round(await clubMorale(c.id)*10)/10,players:squad.map(p=>visible(p))};});
 route('get','/api/club-statistics/:id',async req=>{const games=await db.select().from(matches).where(eitherClub(eq(matches.homeClubId,req.params.id),eq(matches.awayClubId,req.params.id)));const [world]=await db.select().from(worldState);const seasons=[...new Set([world?.season||1,...games.map(g=>g.season)])].sort((a,b)=>b-a);const chosen=req.query.season&&req.query.season!=='total'?games.filter(g=>g.season===Number(req.query.season)):games;let wins=0,draws=0,losses=0,forPoints=0,against=0,attendance=0;const totals:Record<string,number>={};for(const g of chosen){const home=g.homeClubId===req.params.id,a=home?g.homeScore:g.awayScore,b=home?g.awayScore:g.homeScore;wins+=Number(a>b);draws+=Number(a===b);losses+=Number(a<b);forPoints+=a;against+=b;const report:any=g.matchReport;attendance+=home?report.attendance:0;totals.assists=(totals.assists||0)+(report.individualStats||[]).filter((p:any)=>p.side===(home?'home':'away')).reduce((sum:number,p:any)=>sum+(p.assists||0),0);for(const [key,val] of Object.entries(report[home?'homeStats':'awayStats']||{}))totals[key]=(totals[key]||0)+Number((val as any).antal||0);}return {seasons,matches:chosen.length,wins,draws,losses,forPoints,against,attendance:Math.round(attendance/Math.max(1,chosen.filter(g=>g.homeClubId===req.params.id).length)),totals};});
 route('get','/api/training-gains/:clubId',async req=>(await records('training-gain')).filter(g=>g.clubId===req.params.clubId&&Date.now()-+new Date(g.date)<7*86400000));
 route('get','/api/recruitment',async()=>{const teams=await db.select().from(clubs);return ({coaches:COACHES.map(c=>({...c,hiredBy:teams.find(t=>(t.coach as any)?.id===c.id)?{id:teams.find(t=>(t.coach as any)?.id===c.id)!.id,name:teams.find(t=>(t.coach as any)?.id===c.id)!.name}:null})),artifacts:ARTIFACTS,mercenaries:(await db.select().from(players)).filter(p=>p.isMercenary&&!p.clubId&&!p.isDeceased).map(p=>({...visible(p),fee:mercenaryFee(p.attributes as any)}))});});
 route('post','/api/recruitment/:kind',async req=>db.transaction(async(tx:any)=>{
  const [club]=await tx.select().from(clubs).where(eq(clubs.id,req.body.clubId)).for('update');if(!club||club.isBot)throw Error('Laget saknas.');
  if(req.params.kind==='coach'){await tx.execute(sql`SELECT pg_advisory_xact_lock(719090)`);if((await tx.select().from(clubs)).some((c:any)=>c.coach?.id===req.body.id&&c.id!==club.id))throw Error('Tränaren har redan avtal med ett annat lag.');const coach=COACHES.find(c=>c.id===req.body.id);if(!coach)throw Error('Tränaren saknas.');const allocated=Object.values(club.trainingPoints).reduce((s:number,n:any)=>s+Number(n),0);if(Number(allocated)>6+coach.trainingBonus)throw Error('Minska träningsfördelningen före tränarbytet.');await tx.update(clubs).set({coach}).where(eq(clubs.id,club.id));return {success:true};}
  let price=0,category='';
  if(req.params.kind==='mercenary'){const [p]=await tx.select().from(players).where(eq(players.id,Number(req.body.id))).for('update');if(!p?.isMercenary||p.clubId||p.isDeceased)throw Error('Fribrytaren är inte ledig.');const squad=await tx.select().from(players).where(eq(players.clubId,club.id));if(squad.length>=99)throw Error('Truppen är full.');price=mercenaryFee(p.attributes as any);category='Fribrytare';await put('morale-change','morale-mercenary-'+p.id+'-'+Date.now(),{clubId:club.id,date:new Date().toISOString(),penalty:p.race===club.race?0:5},tx);const used=new Set(squad.map((p:any)=>p.shirtNumber));let n=1;while(used.has(n))n++;await tx.update(players).set({clubId:club.id,shirtNumber:n}).where(eq(players.id,p.id));await put('mercenary-contract','contract-'+p.id,{playerId:p.id,clubId:club.id,hiredAt:new Date().toISOString()},tx);}
  else if(req.params.kind==='artifact')throw Error('Artefakter köps genom budgivning på artefaktmarknaden.');
  else throw Error('Okänd kategori.');if(club.gold<price)throw Error('Du har inte tillräckligt med guld.');await tx.update(clubs).set({gold:club.gold-price}).where(eq(clubs.id,club.id));await put('ledger','recruit-'+randomUUID(),{clubId:club.id,category,amount:-price,date:new Date().toISOString()},tx);return {success:true};
 }));
 route('get','/api/scout-routes/:clubId',async req=>{const [c]=await db.select().from(clubs).where(eq(clubs.id,req.params.clubId));if(!c)throw Error('Laget saknas.');const s=await record('scout-'+c.id);const location=PLACES.find(p=>p.id===s?.locationId)||PLACES.find(p=>p.name===c.hometown)||PLACES[0];return {location,neighbors:nearbyPlaces(location.id)};});
 async function tipsData(clubId:string,tx:any=db){const [world]=await tx.select().from(worldState);const season=world?.season||1;const fixtures=(await records('fixture',tx)).filter(f=>f.division==='Kejsarserien'&&(f.season||1)===season).sort((a,b)=>a.date.localeCompare(b.date));const round=fixtures.find(f=>!f.played)?.round??fixtures.at(-1)?.round??1;const games=fixtures.filter(f=>f.round===round),all=await tx.select().from(clubs),coupons=(await records('tips-coupon',tx)).filter(c=>(c.season||1)===season);const deadline=games[0]?.date;return {season,round,deadline,stake:8000,pot:coupons.filter(c=>c.round===round).reduce((s,c)=>s+(c.stake||0),0),paid:!!coupons.find(c=>c.round===round&&c.clubId===clubId&&c.stake===8000),open:!!deadline&&Date.now()<+new Date(deadline),games:games.map(g=>({...g,homeName:all.find(c=>c.id===g.homeId)?.name,awayName:all.find(c=>c.id===g.awayId)?.name})),picks:coupons.find(c=>c.clubId===clubId&&c.round===round)?.picks||{},top:coupons.filter(c=>fixtures.some(f=>f.round===c.round&&f.played)).map(c=>({name:all.find(x=>x.id===c.clubId)?.name,round:c.round,points:fixtures.filter(f=>f.round===c.round&&f.played&&c.picks[f.id]===(f.homeScore>f.awayScore?'1':f.homeScore===f.awayScore?'X':'2')).length})).sort((a,b)=>b.points-a.points)};}
 route('get','/api/tips/:clubId',async req=>tipsData(req.params.clubId));
 route('post','/api/tips/:clubId',async req=>db.transaction(async(tx:any)=>{const data=await tipsData(req.params.clubId,tx);const [c]=await tx.select().from(clubs).where(eq(clubs.id,req.params.clubId)).for('update');if(!c||c.isBot||!data.open)throw Error('Tipsomgången är stängd.');if(data.games.some(g=>!['1','X','2'].includes(req.body.picks?.[g.id])))throw Error('Tippa alla matcherna.');const id='tips-'+(data.season===1?'':data.season+'-')+data.round+'-'+c.id,previous=await record(id,tx),stake=8000;if(previous?.stake!==stake){if(c.gold<stake)throw Error('Insatsen är 8 000 guld.');await tx.update(clubs).set({gold:c.gold-stake}).where(eq(clubs.id,c.id));await put('ledger','tips-entry-'+id,{clubId:c.id,amount:-stake,category:'Tipsinsats',date:new Date().toISOString()},tx);}const picks=Object.fromEntries(data.games.map(g=>[g.id,req.body.picks[g.id]]));await put('tips-coupon',id,{clubId:c.id,season:data.season,round:data.round,picks,stake,date:new Date().toISOString()},tx);return {success:true};}));
}

