import {Express} from 'express';import {db} from '../db';import {players,clubs,matches} from '../db/schema';import {desc,eq} from 'drizzle-orm';
import {records} from './records';import {ARTIFACTS} from '../constants/market';
export function registerLore(app:Express){app.get('/api/lore',async(_req,res)=>{try{const [rich]=await db.select().from(players).where(eq(players.isMercenary,false)).orderBy(desc(players.wage)).limit(1);const games=await db.select().from(matches),teams=await db.select().from(clubs);const entries:any[]=[
 {category:'Ur krönikorna',label:'Berunias första arena var en handelsgård. När den tredje korgen förstörde tullhuset förbjöd kejsaren fler än två sidokorgar.'},
 {category:'Ur krönikorna',label:'Skogsbyarnas alver syr löv på lagets resmantlar. Ett silverlöv betyder en bortaseger som ingen väntade sig.'},
 {category:'Ur krönikorna',label:'En dvärgdomare sägs ha blåst slutsignalen med en tekittel när visselpipan frös fast i skägget.'},
 {category:'Ur krönikorna',label:'I Mambenna anses det ge otur att putsa vänsterskon före högerskon på matchdagen.'},
 {category:'Speltips',label:'Två reserver i samma ruta: den vänstra får första chansen när en spelare skadas.'},
 {category:'Speltips',label:'En stark skytt behöver inte vara en bra målvakt. Jämför positionspoängen när du väljer uppställning.'},
 {category:'Ur krönikorna',label:'Kejsarens hovkock vägrar servera kålsoppa före tvekampen. Det räcker med en sorts oro på läktaren.'}];
 if(rich)entries.push({category:'Spelarrekord',before:'Högst angiven spelarlön har ',label:rich.name,entity:{kind:'player',id:rich.id},after:': '+rich.wage.toLocaleString('sv-SE')+' guld.'});
 if(games.length){for(const category of ['injuries','goals']){const score=(m:any)=>{const r=m.matchReport;return category==='injuries'?(r.injuries.home.length+r.injuries.away.length):r.events.filter((e:any)=>e.type==='GOAL_NORMAL'||e.type==='GOAL_BASKET').length};const sorted=[...games].sort((a,b)=>score(b)-score(a)),best:any=sorted[0];entries.push({category:'Matchrekord',before:category==='injuries'?'Flest skador noterades i ':'Flest mål och korgmål noterades i ',label:best.matchReport.homeClub.name+' – '+best.matchReport.awayClub.name,entity:{kind:'match',id:best.id},after:': '+score(best)+'.'});}
 let best={count:0,id:''};for(const c of teams){let count=0;for(const m of [...games].sort((a,b)=>+new Date(a.playedAt)-+new Date(b.playedAt))){if(m.homeClubId!==c.id&&m.awayClubId!==c.id)continue;const own=m.homeClubId===c.id?m.homeScore:m.awayScore,other=m.homeClubId===c.id?m.awayScore:m.homeScore;count=own>=other?count+1:0;if(count>best.count)best={count,id:c.id}}}if(best.count)entries.push({category:'Lagrekord',before:'Längsta sviten utan förlust har ',label:teams.find(c=>c.id===best.id)?.name,entity:{kind:'club',id:best.id},after:': '+best.count+' matcher.'});}
 const playerSales=(await records('auction')).filter(a=>a.closed&&!a.cancelled&&a.bidderId),artifactSales=(await records('artifact-auction')).filter(a=>a.closed&&!a.cancelled&&a.bidderId);
 const recordSale=[...playerSales].sort((a,b)=>b.price-a.price)[0];if(recordSale){const p=(await db.select().from(players)).find(p=>p.id===recordSale.playerId);entries.push({category:'Transferrekord',before:'Rikets dyraste spelarförsäljning är ',label:p?.name||'en tidigare spelare',entity:p?{kind:'player',id:p.id}:undefined,after:': '+recordSale.price.toLocaleString('sv-SE')+' guld.'});}
 const spending=new Map<string,number>();for(const a of playerSales)spending.set(a.bidderId,(spending.get(a.bidderId)||0)+a.price);const biggest=[...spending].sort((a,b)=>b[1]-a[1])[0];if(biggest)entries.push({category:'Transferrekord',before:'Mest guld på spelarköp har ',label:teams.find(c=>c.id===biggest[0])?.name||'ett försvunnet lag',entity:{kind:'club',id:biggest[0]},after:' lagt: '+biggest[1].toLocaleString('sv-SE')+' guld.'});
 const artifactSale=[...artifactSales].sort((a,b)=>b.price-a.price)[0];if(artifactSale)entries.push({category:'Artefaktrekord',before:'Dyraste artefakten som sålts är ',label:ARTIFACTS.find(a=>a.id===artifactSale.artifactId)?.name||'en okänd artefakt',after:' för '+artifactSale.price.toLocaleString('sv-SE')+' guld till '+(teams.find(c=>c.id===artifactSale.bidderId)?.name||'ett lag')+'.',entity:{kind:'club',id:artifactSale.bidderId}});
 const seasonGoals=new Map<string,{id:number;name:string;season:number;goals:number}>(),hurt=new Map<string,{id:number;name:string;matchId:string;count:number}>();for(const game of games){const report:any=game.matchReport;for(const p of report.individualStats||[]){const key=game.season+'-'+p.id,row=seasonGoals.get(key)||{id:p.id,name:p.name,season:game.season,goals:0};row.goals+=(p.stats?.skott?.lyckade||0);seasonGoals.set(key,row);}for(const e of report.events||[])if(e.type==='FIGHT_RESULT'&&e.important&&e.playerId){const key=game.id+'-'+e.playerId,row=hurt.get(key)||{id:e.playerId,name:e.playerName,matchId:game.id,count:0};row.count++;hurt.set(key,row);}}
 const scorer=[...seasonGoals.values()].sort((a,b)=>b.goals-a.goals)[0];if(scorer?.goals)entries.push({category:'Säsongsrekord',before:'Flest vanliga mål under en säsong har ',label:scorer.name,entity:{kind:'player',id:scorer.id},after:' gjort: '+scorer.goals+' mål under säsong '+scorer.season+'.'});const bruiser=[...hurt.values()].sort((a,b)=>b.count-a.count)[0];if(bruiser?.count)entries.push({category:'Matchrekord',before:'Flest motståndare skadade av en spelare i samma match: ',label:bruiser.name,entity:{kind:'player',id:bruiser.id},after:' med '+bruiser.count+' skador.'});
 res.json(entries[Math.floor(Math.random()*entries.length)]);
 }catch(e:any){res.status(500).json({error:e.message})}})}
