import {magicThresholds,earnedMagicLevel} from '../engine/magicEconomy';
import {Express} from 'express';import {db} from '../db';import {clubs,players,worldState} from '../db/schema';import {eq} from 'drizzle-orm';import {record,put,records} from './records';import {SPELLS,spellById,magicCapacity,magicLevel,activeSpells} from '../constants/spells';
async function hasStaff(id:string,tx:any=db){const [world]=await tx.select().from(worldState);return (await records('artifact-item',tx)).some(i=>i.clubId===id&&i.artifactId==='moon-staff'&&!i.listed&&i.expiresSeason>=world.season)}
function regenerated(state:any,budget:number){const capacity=magicCapacity(budget),now=Date.now(),mana=Math.min(capacity,(state?.mana??0)+Math.max(0,now-(state?.at??now))/604800000*capacity);return {mana,at:now,capacity,cooldowns:state?.cooldowns||{}}}
export function registerMagic(app:Express){
 const route=(m:'get'|'post',path:string,fn:(r:any)=>Promise<any>)=>app[m](path,async(req,res)=>{try{res.json(await fn(req))}catch(e:any){res.status(400).json({error:e.message})}});
 route('get','/api/magic-state/:clubId',async req=>{const [club]=await db.select().from(clubs).where(eq(clubs.id,req.params.clubId));if(!club)throw Error('Laget saknas');const thresholds=magicThresholds(club.id,await db.select().from(clubs));const premiumWeeks=(await record('magic-progress-'+club.id))?.weeks||0;const squad=await db.select().from(players).where(eq(players.clubId,club.id)),state=regenerated(await record('mana-'+club.id),club.magicInvestment);if(!await record('mana-'+club.id))await put('mana','mana-'+club.id,state);const staff=await hasStaff(club.id);return {...state,level:earnedMagicLevel(club.magicInvestment,thresholds,premiumWeeks),thresholds,premiumWeeks,staff,spells:SPELLS.filter(s=>s.race==='all'||s.race===club.race||staff),players:squad.filter(p=>!p.isDeceased).map(p=>({id:p.id,name:p.name,effects:activeSpells(p.artifacts as string[]).map(s=>s.name)}))};});
 route('post','/api/magic-cast/:clubId',async req=>db.transaction(async(tx:any)=>{const [club]=await tx.select().from(clubs).where(eq(clubs.id,req.params.clubId)).for('update');if(!club||club.isBot)throw Error('Laget saknas');const thresholds=magicThresholds(club.id,await tx.select().from(clubs)),premiumWeeks=(await record('magic-progress-'+club.id,tx))?.weeks||0;const state=regenerated(await record('mana-'+club.id,tx),club.magicInvestment),spell=spellById(req.body.spellId),squad=await tx.select().from(players).where(eq(players.clubId,club.id));if(!spell||spell.level>earnedMagicLevel(club.magicInvestment,thresholds,premiumWeeks)||(spell.race!=='all'&&spell.race!==club.race&&!await hasStaff(club.id,tx)))throw Error('Besvärjelsen är låst.');if(state.mana<spell.mana)throw Error('För lite mana.');if(spell.craft){if(club.race!=='orc')throw Error('Riten tillhör orchernas blodsbundna tradition.');const [world]=await tx.select().from(worldState),id='crafted-dragon-'+club.id+'-'+world.season;if(await record(id,tx))throw Error('Riten har redan utförts denna säsong.');await put('artifact-item',id,{artifactId:'dragon-blood',clubId:club.id,playerId:null,listed:false},tx);await put('mana','mana-'+club.id,{...state,mana:state.mana-spell.mana},tx);return {success:true};}if(spell.matchEffect){const f=await record(String(req.body.fixtureId),tx);if(!f||(spell.matchEffect==='ward'?![f.homeId,f.awayId].includes(club.id):f.homeId!==club.id)||f.played||Date.now()>=+new Date(f.date)||+new Date(f.date)>Date.now()+24*3600000)throw Error('Välj en kommande hemmamatch inom 24 timmar.');await put('match-weather',(spell.matchEffect==='ward'?'ward-':spell.matchEffect==='baskets'?'baskets-':spell.matchEffect==='chains'?'chains-':'weather-')+f.id,{fixtureId:f.id,clubId:club.id,spellId:spell.id,effect:spell.matchEffect,expires:+new Date(f.date)+3600000},tx);await put('mana','mana-'+club.id,{...state,mana:state.mana-spell.mana,cooldowns:{}},tx);return {success:true};}
 const p=squad.find((p:any)=>p.id===Number(req.body.playerId));if(!p||p.isDeceased||p.isMercenary)throw Error('Välj en egen levande spelare.');if(activeSpells(p.artifacts as string[]).some(s=>s.id===spell.id))throw Error('Samma besvärjelse är redan aktiv.');await tx.update(players).set({artifacts:[...p.artifacts,'magic:'+spell.id+':'+(spell.matches||1)]}).where(eq(players.id,p.id));await put('mana','mana-'+club.id,{...state,mana:state.mana-spell.mana,cooldowns:{}},tx);return {success:true};}));
 route('post','/api/magic/:clubId',async req=>db.transaction(async(tx:any)=>{const [c]=await tx.select().from(clubs).where(eq(clubs.id,req.params.clubId)).for('update');const cost=Number(req.body.cost);if(!c||c.isBot||!Number.isInteger(cost)||cost<0||cost>100000)throw Error('Ange 0–100 000 guld.');const activation=0;if(c.gold<activation)throw Error('För lite guld för att höja satsningen.');if(activation)await put('ledger','magic-activation-'+c.id+'-'+Date.now(),{clubId:c.id,category:'Magisatsning – aktivering',amount:-activation,date:new Date().toISOString()},tx);const previous=regenerated(await record('mana-'+c.id,tx),c.magicInvestment);const thresholds=magicThresholds(c.id,await tx.select().from(clubs));if(cost<thresholds.level3)await put('magic-progress','magic-progress-'+c.id,{weeks:0},tx);await put('mana','mana-'+c.id,{...previous,mana:Math.min(previous.mana,magicCapacity(cost))},tx);await tx.update(clubs).set({magicInvestment:cost,gold:c.gold-activation}).where(eq(clubs.id,c.id));return {success:true};}));
}
