import {and,eq,or,sql} from 'drizzle-orm';
import {worldState} from '../db/schema';
import {Express} from 'express';import {db} from '../db';import {clubs,players,matches} from '../db/schema';import {records,record,put} from './records';
export async function teamNews(tx:any,clubId:string,id:string,title:string,body:string,entity?:any){await put('team-news','news-'+id+'-'+clubId,{clubId,title,body,date:new Date().toISOString(),entity},tx)}
export async function statisticSeasons(){const [w]=await db.select({season:worldState.season}).from(worldState);const rows=await db.selectDistinct({season:matches.season}).from(matches);return [...new Set([w?.season||1,...rows.map(r=>r.season)])].sort((a,b)=>b-a)}
export async function statistics(division?:string,season="total",forClub?:string,forPlayer?:number){
 const teams=await db.select({id:clubs.id,name:clubs.name,merit:clubs.merit,division:clubs.division}).from(clubs),ps=await db.select({id:players.id,name:players.name,race:players.race,isDeceased:players.isDeceased}).from(players).where(forPlayer?eq(players.id,forPlayer):undefined),seasons=await statisticSeasons();
 const games=await db.select({homeClubId:matches.homeClubId,awayClubId:matches.awayClubId,matchReport:sql<any>`jsonb_build_object('homeClub',jsonb_build_object('id',${matches.matchReport}->'homeClub'->'id','name',${matches.matchReport}->'homeClub'->'name'),'awayClub',jsonb_build_object('id',${matches.matchReport}->'awayClub'->'id','name',${matches.matchReport}->'awayClub'->'name'),'engineVersion',${matches.matchReport}->'engineVersion','individualStats',${matches.matchReport}->'individualStats','startingLineups',${matches.matchReport}->'startingLineups','events',${matches.matchReport}->'events','homeStats',${matches.matchReport}->'homeStats','awayStats',${matches.matchReport}->'awayStats')`}).from(matches).where(and(division?eq(matches.division,division):undefined,season!=='total'?eq(matches.season,Number(season)):undefined,forClub?or(eq(matches.homeClubId,forClub),eq(matches.awayClubId,forClub)):undefined,forPlayer?sql`${matches.matchReport}->'individualStats' @> ${JSON.stringify([{id:forPlayer}])}::jsonb`:undefined));
 const teamIndex=new Map(teams.map(t=>[t.id,t])),playerIndex=new Map(ps.map(p=>[p.id,p]));
 const people=new Map<number,any>(),teamRows=new Map<string,any>();
 const add=(row:any,stats:any)=>{for(const [k,v] of Object.entries(stats||{}) as any){const a=row.stats[k]||{antal:0,lyckade:0,viktat:0};a.antal+=v.antal||0;a.lyckade+=v.lyckade??v.vunna??0;a.viktat+=v.viktat||0;row.stats[k]=a;}};
 for(const game of games){const m:any=game.matchReport;for(const side of ['home','away']){const clubId=side==='home'?game.homeClubId:game.awayClubId,c=teamIndex.get(clubId);const row=teamRows.get(clubId)||{id:clubId,name:c?.name||m[side+'Club'].name,matches:0,weightedMatches:0,stats:{},assists:0,assistWeighted:0};row.weightedMatches+=Number(m.engineVersion>=9);row.assistWeighted+=(m.individualStats||[]).filter((p:any)=>p.side===side).reduce((sum:number,p:any)=>sum+(p.assistWeighted||0),0);row.matches++;add(row,m[side+'Stats']);row.assists+=m.events.filter((e:any)=>e.teamSide===side&&e.assistPlayerId).length;teamRows.set(clubId,row);}
  for(const person of m.individualStats||[]){if(forPlayer&&person.id!==forPlayer)continue;if(forClub&&m[person.side+'Club'].id!==forClub)continue;const p=playerIndex.get(person.id),historical=m[person.side+'Club'],clubId=historical.id,c=teamIndex.get(clubId);const row=people.get(person.id)||{id:person.id,name:p?.name||person.name,race:p?.race||person.race,exists:!!p,isDeceased:!!p?.isDeceased,clubId,clubName:historical.name||c?.name||'Inget lag',clubs:[],matches:0,weightedMatches:0,assists:0,assistWeighted:0,stats:{}};
   const appeared=m.startingLineups[person.side].some((x:any)=>x.id===person.id)||m.events.some((e:any)=>e.type==='SUBSTITUTION'&&e.playerId===person.id);if(!appeared)continue;
   if(!row.clubs.some((c:any)=>c.id===clubId))row.clubs.push({id:clubId,name:historical.name||c?.name||'Inget lag'});row.weightedMatches+=Number(m.engineVersion>=9);row.matches++;row.assists+=person.assists||m.events.filter((e:any)=>e.assistPlayerId===person.id).length;row.assistWeighted+=person.assistWeighted||0;add(row,person.stats);people.set(person.id,row);
  }
 }
 return {seasons,players:[...people.values()],teams:[...teamRows.values()],top:teams.filter(c=>c.merit>0&&(!division||c.division===division)).sort((a,b)=>b.merit-a.merit).slice(0,100).map(c=>({id:c.id,name:c.name,merit:c.merit})),matches:[]};
}
export function registerNews(app:Express){app.post('/api/team-news/:clubId/read',async(req:any,res)=>{const c=(await db.select().from(clubs)).find(c=>c.id===req.params.clubId&&c.userId===req.arenaUser.userId);if(!c)return res.status(403).json({error:'Nyheten tillhör inte ditt lag.'});await put('news-read','news-read-'+c.id+'-'+String(req.body.id),{clubId:c.id,newsId:String(req.body.id),date:new Date().toISOString()});res.json({success:true})});app.get('/api/team-news/:clubId',async(req:any,res)=>{try{const teams=await db.select().from(clubs),club=teams.find(c=>c.id===req.params.clubId);if(!club||club.userId!==req.arenaUser?.userId)return res.status(403).json({error:'Lagets post är privat.'});const news=(await records('team-news')).filter(n=>n.clubId===club.id);for(const g of await db.select({id:matches.id,homeClubId:matches.homeClubId,awayClubId:matches.awayClubId,playedAt:matches.playedAt,homeScore:matches.homeScore,awayScore:matches.awayScore}).from(matches).where(or(eq(matches.homeClubId,club.id),eq(matches.awayClubId,club.id)))){if(g.homeClubId!==club.id&&g.awayClubId!==club.id)continue;news.push({id:'match-'+g.id,title:'En ny match är spelad',date:g.playedAt,body:`${teams.find(c=>c.id===g.homeClubId)?.name} – ${teams.find(c=>c.id===g.awayClubId)?.name}: ${g.homeScore}–${g.awayScore}.`,matchId:g.id});}for(const g of (await records('guestbook')).filter(g=>g.targetClubId===club.id&&g.clubId!==club.id))news.push({id:'guest-'+g.id,title:'En hälsning i gästboken',date:g.date,body:g.author+' från '+g.clubName+' har skrivit i din gästbok.',entity:{kind:'club',id:club.id}});const read=new Set((await records('news-read')).filter(r=>r.clubId===club.id).map(r=>r.newsId));res.json(news.map(n=>({...n,read:read.has(n.id)})).sort((a,b)=>+new Date(b.date)-+new Date(a.date)).slice(0,100));}catch(e:any){res.status(500).json({error:e.message})}})}
