import {seasonPrizeNotice} from './seasonPrizeNotice';
import {worldMarketQuality,marketAttributes} from '../engine/marketQuality';
import {seasonPrize} from '../constants/prizes';
import {progressLoanConsequences,overdueEffects} from './loanConsequences';
import {Express} from 'express';import {db} from '../db';import {clubs,players,gameRecords,worldState} from '../db/schema';import {eq,sql} from 'drizzle-orm';import {records,record,put} from './records';import {PLACES} from '../constants/geography';import {venueCatalog} from '../constants/venues';import {weatherFor} from '../engine/weather';import {generateSinglePlayer,calculateWage,generateAggression} from '../engine/playerGenerator';import {SeededRNG} from '../engine/matchEngine';import {COACHES} from '../constants/market';import {randomUUID} from 'node:crypto';
import {LOANS} from '../constants/loans';export {LOANS};
import {progressSolvency} from './solvency';
export async function initializeRevision8(){if(await record('revision-v8'))return;await db.transaction(async(tx:any)=>{if(await record('revision-v8',tx))return;for(const p of await tx.select().from(players)){const attributes={...p.attributes},rng=new SeededRNG(p.id*197+832);attributes.aggressivitet=generateAggression(p.race,()=>rng.next());await tx.update(players).set({attributes,wage:calculateWage(attributes)}).where(eq(players.id,p.id));}for(const c of await tx.select().from(clubs))if(c.coach){const coach=COACHES.find(p=>p.id===c.coach.id);if(coach)await tx.update(clubs).set({coach}).where(eq(clubs.id,c.id));}await put('system','revision-v8',{date:new Date().toISOString()},tx);});}
export async function progressEconomy(now:Date){await progressLoanConsequences(now);await progressSolvency(now)}
export async function releaseMarketPlayers(now:Date){const day=weatherFor('',now).date;await db.transaction(async(tx:any)=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(719082)`);if(await record('market-day-'+day,tx))return;const weekday=new Date(day+'T12:00:00Z').getUTCDay();const races=([['human','elf'],['dwarf','orc'],['human','elf'],['dwarf','goblin'],['human','orc'],['elf','dwarf'],['orc','human','troll']][weekday]) as any[];const reference=worldMarketQuality(await tx.select().from(players));for(let i=0;i<races.length;i++){const race=races[i],homes=PLACES.filter(p=>p.race===race),home=homes[Math.floor(Math.random()*homes.length)];const p=generateSinglePlayer(0,race,'',home.name,1,['goalkeeper','defender','midfielder','attacker'][Math.floor(Math.random()*4)] as any);p.attributes=marketAttributes(p.attributes,reference);p.wage=calculateWage(p.attributes);const {id,positionRatingsWithForm,positionRatingsWithoutForm,...row}=p;const [created]=await tx.insert(players).values({...row,clubId:null}).returning();await put('auction','auction-'+randomUUID(),{playerId:created.id,sellerId:null,price:Math.max(100,Math.round(p.wage*5)),bidderId:null,endsAt:new Date(+now+7*86400000).toISOString(),closed:false},tx);}await put('system','market-day-'+day,{date:day},tx);});}
export async function awardSeason(now:Date){const [currentWorld]=await db.select().from(worldState);const f=(await records('fixture')).filter(f=>(f.season||1)===currentWorld.season);if(!f.length||f.some(f=>!f.played)||Math.max(...f.map(f=>f.round))<18)return;await db.transaction(async(tx:any)=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(719083)`);const [w]=await tx.select().from(worldState);if(await record('season-award-'+w.season,tx))return;const all=await tx.select().from(clubs);for(const division of new Set<string>(all.map((c:any)=>c.division))){const ordered=all.filter((c:any)=>c.division===division).sort((a:any,b:any)=>(b.wins*3+b.draws)-(a.wins*3+a.draws)||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||a.id.localeCompare(b.id));const tier=division==='Kejsarserien'?0:Number(division.match(/Division (\d)/)?.[1]||3);for(let i=0;i<ordered.length;i++){const prize=seasonPrize(tier,i+1);if(!prize)continue;await tx.update(clubs).set({gold:sql`${clubs.gold}+${prize}`}).where(eq(clubs.id,ordered[i].id));await put('ledger','season-prize-'+w.season+'-'+ordered[i].id,{clubId:ordered[i].id,category:'Säsongspris, plats '+(i+1),amount:prize,date:now.toISOString()},tx);await seasonPrizeNotice(tx,ordered[i],w.season,division,i+1,prize,now.toISOString());} if(division==='Kejsarserien'&&ordered[0])await put('trophy','kodudorf-'+w.season,{clubId:ordered[0].id,season:w.season,name:'Kodudorfpokalen',date:now.toISOString()},tx);}await put('system','season-award-'+w.season,{date:now.toISOString()},tx);});}
export function registerProgression(app:Express){const route=(method:'get'|'post',path:string,fn:(req:any)=>Promise<any>)=>app[method](path,async(req,res)=>{try{res.json(await fn(req))}catch(e:any){res.status(400).json({error:e.message})}});
 route('get','/api/weather',async req=>weatherFor(String(req.query.place||'')));
 route('get','/api/venues',async()=>venueCatalog(await db.select().from(clubs)));
 route('get','/api/club-extras/:id',async req=>({image:(await record('club-image-'+req.params.id))?.data||null,trophies:(await records('trophy')).filter(t=>t.clubId===req.params.id)}));
 route('get','/api/loans/:clubId',async req=>({offers:LOANS,loans:(await records('loan')).filter(l=>l.clubId===req.params.clubId),effects:overdueEffects(await records('loan'),req.params.clubId,new Date())}));
 route('post','/api/loans/:clubId',async req=>db.transaction(async(tx:any)=>{const [c]=await tx.select().from(clubs).where(eq(clubs.id,req.params.clubId)).for('update');if(!c||c.isBot||c.userId!==req.arenaUser.userId)throw Error('Laget tillhör inte dig.');if(req.body.repay){const l=await record(req.body.repay,tx);if(!l||l.clubId!==c.id||l.paid)throw Error('Lånet saknas.');if(c.gold<l.total)throw Error('Kassan räcker inte till hela återbetalningen.');await tx.update(clubs).set({gold:c.gold-l.total}).where(eq(clubs.id,c.id));await put('loan',l.id,{...l,paid:true,paidAt:new Date().toISOString()},tx);const solvency=await record('solvency-'+c.id,tx);if(solvency&&(await records('loan',tx)).filter(x=>x.clubId===c.id&&!x.paid).reduce((s,x)=>s+x.total,0)<=2000000)await put('solvency',solvency.id,{...solvency,debtSince:null},tx);await put('ledger','repayment-'+l.id,{clubId:c.id,category:'Återbetalning till '+l.lender,amount:-l.total,date:new Date().toISOString()},tx);return {success:true};}const offer=LOANS.find(l=>l.id===req.body.offer);if(!offer||c.merit<offer.merit)throw Error('Meriten räcker inte för detta lån.');if((await records('loan',tx)).some(l=>l.clubId===c.id&&(l.offerId===offer.id||l.lender===offer.lender)&&Date.now()-+new Date(l.takenAt)<7*86400000))throw Error('Varje långivare utfärdar ett nytt kreditbrev högst en gång per vecka.');const id='loan-'+randomUUID(),now=new Date();await put('loan',id,{...offer,id,offerId:offer.id,clubId:c.id,paid:false,takenAt:now.toISOString(),dueAt:new Date(+now+offer.weeks*7*86400000).toISOString()},tx);const debt=(await records('loan',tx)).filter(x=>x.clubId===c.id&&!x.paid).reduce((s,x)=>s+x.total,0);if(debt>2000000){const solvency=await record('solvency-'+c.id,tx)||{};await put('solvency','solvency-'+c.id,{...solvency,debt,debtSince:solvency.debtSince||now.toISOString(),cashSince:null},tx);}await tx.update(clubs).set({gold:c.gold+offer.amount}).where(eq(clubs.id,c.id));await put('ledger','borrow-'+id,{clubId:c.id,category:'Lån från '+offer.lender,amount:offer.amount,date:now.toISOString()},tx);return {success:true};}));
 route('post','/api/club-settings/:clubId',async req=>db.transaction(async(tx:any)=>{const [c]=await tx.select().from(clubs).where(eq(clubs.id,req.params.clubId)).for('update');if(!c||c.isBot||c.userId!==req.arenaUser.userId)throw Error('Laget tillhör inte dig.');const update:any={};let cost=0;if(req.body.shortName!==undefined){const shortName=String(req.body.shortName).trim();if(!shortName||shortName.length>25)throw Error('Kortnamnet ska ha 1–25 tecken.');update.shortName=shortName;}if(req.body.name!==undefined){const name=String(req.body.name).trim();if(name.length<3||name.length>50)throw Error('Lagnamnet ska ha 3–50 tecken.');if((await tx.select().from(clubs)).some((t:any)=>t.id!==c.id&&t.name.toLocaleLowerCase('sv')===name.toLocaleLowerCase('sv')))throw Error('Lagnamnet är upptaget.');if(name!==c.name){update.name=name;cost+=100000;}}if(req.body.hometown!==undefined){const place=PLACES.find(p=>p.name===req.body.hometown);if(!place)throw Error('Välj en ort på kartan.');if(place.name!==c.hometown){update.hometown=place.name;cost+=100000;}}if(cost>0&&c.gold<cost)throw Error('Kassan räcker inte.');if(req.body.image!==undefined){const data=String(req.body.image);if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data))throw Error('Välj PNG, JPEG eller WebP.');const bytes=Buffer.from(data.split(',')[1],'base64');const valid=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||bytes[0]===255&&bytes[1]===216||bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid||bytes.length>500000)throw Error('Bilden ska vara en giltig bild under 500 kB.');await put('club-image','club-image-'+c.id,{data},tx);}if(Object.keys(update).length)await tx.update(clubs).set({...update,gold:c.gold-cost}).where(eq(clubs.id,c.id));if(cost)await put('ledger','identity-'+randomUUID(),{clubId:c.id,amount:-cost,category:'Klubbnamn / hemort',date:new Date().toISOString()},tx);return {success:true};}));
}
