import {Express} from 'express';import {db} from '../db';import {clubs,players,matches,worldState} from '../db/schema';import {eq,sql} from 'drizzle-orm';import {records,record,put} from './records';import {statistics,statisticSeasons} from './newsStatistics';import {randomUUID} from 'node:crypto';import {PLACES} from '../constants/geography';import {venueCatalog,standardVenue,bookingFee} from '../constants/venues';
export function registerRevision11(app:Express){const route=(m:'get'|'post',path:string,fn:(r:any)=>Promise<any>)=>app[m](path,async(req,res)=>{try{res.json(await fn(req))}catch(e:any){res.status(400).json({error:e.message})}});
route('get','/api/imperial-honours/:id',async req=>{const honours=(await records('legend')).filter(l=>l.playerId===Number(req.params.id));return honours.filter(l=>!l.test||!honours.some(other=>!other.test&&other.season===l.season&&other.discipline===l.discipline));});
route('get','/api/tips-results',async req=>{const teams=await db.select().from(clubs),results=await records('tips-result'),coupons=await records('tips-coupon');const rounds=results.map(r=>({...r,season:r.season||1,winners:r.winners.map((id:string)=>({id,name:teams.find(c=>c.id===id)?.name||'Tidigare lag'})),entries:r.entries||coupons.filter(c=>c.round===r.round&&(c.season||1)===(r.season||1)).map(c=>({...c,points:(r.games||[]).filter((g:any)=>c.picks[g.id]===(g.homeScore>g.awayScore?'1':g.homeScore<g.awayScore?'2':'X')).length}))}));const rows=new Map<string,any>();for(const r of rounds.filter(r=>!req.query.season||req.query.season==='total'||r.season===Number(req.query.season)))for(const e of r.entries){const row=rows.get(e.clubId)||{id:e.clubId,name:teams.find(c=>c.id===e.clubId)?.name||'Tidigare lag',points:0,rounds:0,wins:0};row.points+=e.points;row.rounds++;row.wins+=Number(r.winners.some((w:any)=>w.id===e.clubId));rows.set(e.clubId,row);}return {seasons:[...new Set([1,...rounds.map(r=>r.season)])],rounds:rounds.sort((a,b)=>b.season-a.season||b.round-a.round),top:[...rows.values()].sort((a,b)=>b.points-a.points||b.wins-a.wins).slice(0,100)}});
route('get','/api/entity-index',async()=>({retired:(await records('retired')).map(p=>p.id.replace('retired-','')),races:Object.fromEntries((await db.select().from(players)).map(p=>[p.id,p.race])),dead:(await db.select().from(players)).filter(p=>p.isDeceased).map(p=>p.id)}));
route('get','/api/player-history/:id',async req=>{const id=Number(req.params.id),ps=await db.select().from(players),p=ps.find(p=>p.id===id),teams=await db.select().from(clubs),archive=await record('retired-'+id),origin=await record('origin-'+id);const deals=(await records('auction')).filter(a=>a.playerId===id&&a.closed&&!a.cancelled&&a.bidderId).sort((a,b)=>a.endsAt.localeCompare(b.endsAt));const homeId=origin?origin.clubId:deals.length?deals[0].sellerId:p?.clubId;return {exists:!!p&&!archive,deceased:p?.isDeceased,homeClubId:homeId,homeClubName:teams.find(t=>t.id===homeId)?.name||'Ingen hemklubb',currentClubId:p?.clubId,currentClubName:teams.find(t=>t.id===p?.clubId)?.name||'Inget lag',transfers:deals.map(a=>({...a,fromName:teams.find(t=>t.id===a.sellerId)?.name||'Kejsardömets marknad',toName:teams.find(t=>t.id===a.bidderId)?.name}))}});
route('get','/api/series/seasons',async()=>statisticSeasons());
route('get','/api/player-statistics/:id',async req=>{const data=await statistics(undefined,String(req.query.season||'total'),undefined,Number(req.params.id));return {seasons:data.seasons,player:data.players[0]||{matches:0,stats:{},assists:0,clubs:[]}}});
route('get','/api/club-player-statistics/:id',async req=>{const data=await statistics(undefined,String(req.query.season||'total'),req.params.id);return {seasons:data.seasons,players:data.players}});
route('post','/api/player-manage/:id',async req=>db.transaction(async(tx:any)=>{await tx.execute(sql`SELECT pg_advisory_xact_lock(719112)`);const [p]=await tx.select().from(players).where(eq(players.id,Number(req.params.id))).for('update');if(!p)throw Error('Spelaren saknas.');const [c]=await tx.select().from(clubs).where(eq(clubs.id,p.clubId));if(!c||c.userId!==req.arenaUser.userId)throw Error('Spelaren tillhör inte ditt lag.');if(req.body.action==='number'){const n=Number(req.body.number);if(!Number.isInteger(n)||n<1||n>99||(await tx.select().from(players)).some((x:any)=>x.clubId===c.id&&x.id!==p.id&&x.shirtNumber===n))throw Error('Välj ett ledigt nummer 1–99.');await tx.update(players).set({shirtNumber:n}).where(eq(players.id,p.id));return {success:true};}if(req.body.action==='position'){const allowed=['Målvakt','Back','Innermittfält','Yttermittfält','Anfall','Övrig'];if(!allowed.includes(req.body.position))throw Error('Välj en giltig position.');await tx.update(players).set({nominalPosition:req.body.position}).where(eq(players.id,p.id));return {success:true};}if(req.body.action!=='dismiss')throw Error('Okänd åtgärd.');if((await records('auction',tx)).some(a=>a.playerId===p.id&&!a.closed))throw Error('Spelaren är på transfermarknaden.');await put('retired','retired-'+p.id,{name:p.name,clubId:c.id,date:new Date().toISOString(),deceased:p.isDeceased},tx);for(const item of (await records('artifact-item',tx)).filter(i=>i.playerId===p.id))await put('artifact-item',item.id,{...item,playerId:null},tx);const clean=(lineup:any)=>({...lineup,slots:Object.fromEntries(Object.entries(lineup?.slots||{}).map(([k,v]:any)=>[k,{...v,activePlayerIds:(v.activePlayerIds||[v.starterPlayerId]).filter((id:any)=>id&&id!==p.id),reservePlayerIds:(v.reservePlayerIds||[v.subPlayerId]).filter((id:any)=>id&&id!==p.id),starterPlayerId:v.starterPlayerId===p.id?null:v.starterPlayerId,subPlayerId:v.subPlayerId===p.id?null:v.subPlayerId}]))});await tx.update(clubs).set({lineup:clean(c.lineup)}).where(eq(clubs.id,c.id));const presets=await record('presets-'+c.id,tx);if(presets)await put('lineup-presets',presets.id,{...presets,presets:presets.presets.map((v:any)=>v?{...v,lineup:clean(v.lineup)}:v)},tx);for(const plan of (await records('match-lineup',tx)).filter(v=>v.clubId===c.id))await put('match-lineup',plan.id,{...plan,lineup:clean(plan.lineup)},tx);await tx.delete(players).where(eq(players.id,p.id));return {success:true}}));
route('get','/api/guestbook/:id',async req=>(await records('guestbook')).filter(p=>p.targetClubId===req.params.id).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,100));
route('post','/api/guestbook/:id',async req=>db.transaction(async(tx:any)=>{const all=await tx.select().from(clubs),author=all.find((c:any)=>c.userId===req.arenaUser.userId),target=all.find((c:any)=>c.id===req.params.id);if(!author||!target)throw Error('Laget saknas.');const text=String(req.body.text||'').trim();if(!text||text.length>2000)throw Error('Skriv 1–2 000 tecken.');const recent=(await records('guestbook',tx)).filter(p=>p.clubId===author.id&&Date.now()-+new Date(p.date)<60000);if(recent.length>=3)throw Error('Vänta en stund innan du skriver igen.');await put('guestbook','guestbook-'+randomUUID(),{targetClubId:target.id,clubId:author.id,author:author.ownerName,clubName:author.name,text,date:new Date().toISOString()},tx);return {success:true}}));
route('get','/api/mail-unread',async req=>({count:(await records('mail')).filter(m=>m.to===req.arenaUser.userId&&!m.read).length}));
route('get','/api/tips-history/:id',async req=>{const fixtures=(await records('fixture')).filter(f=>f.division==='Kejsarserien'),coupons=(await records('tips-coupon')).filter(c=>c.clubId===req.params.id),teams=await db.select().from(clubs),results=await records('tips-result'),ledger=await records('ledger');return coupons.map(c=>{const result=results.find(r=>r.round===c.round&&(r.season||1)===(c.season||1)),games=result?.games||fixtures.filter(f=>f.round===c.round);return {...c,games:games.map((f:any)=>({...f,homeName:teams.find(t=>t.id===f.homeId)?.name,awayName:teams.find(t=>t.id===f.awayId)?.name,pick:c.picks[f.id],result:f.played?(f.homeScore>f.awayScore?'1':f.homeScore===f.awayScore?'X':'2'):null})),award:ledger.find(l=>l.id==='tips-prize-'+((c.season||1)===1?'':c.season+'-')+c.round+'-'+req.params.id)?.amount||0}}).sort((a,b)=>b.round-a.round)});
route('get','/api/venue/:id',async req=>{const venue=[...venueCatalog(await db.select().from(clubs)),...(await records('fixture')).map(f=>standardVenue(f))].find(v=>v.id===req.params.id||v.name===req.params.id);if(!venue)throw Error('Arenan saknas.');return {...venue,bookingFee:bookingFee(venue)}});
}
