import {MAMBENNA_SETTLEMENTS} from './mambenna';import {Race} from '../types';
const coords=[[52,63],[41,47],[39,16],[57,44],[44,78],[23,46],[30,25],[23,34],[34,41],[65,27],[63,12],[76,10],[73,47],[79,36],[68,59],[70,76]];
const extras:Array<[string,Race,number,number]>=[['Grotthem','troll',91,34],['Dimmervad','troll',36,9],['Rotdjup','troll',10,26],['Kummelås','troll',91,65],['Österborg','human',87,43],['Söderhamn','human',49,86],['Västerport','human',14,53],['Björkebo','elf',21,27],['Kopparvik','dwarf',70,17],['Rödmossen','orc',77,62],['Vassby','goblin',49,45],['Tallås','elf',33,20],['Silverlöv','elf',18,18],['Mossvalla','elf',38,29],['Lövvik','elf',25,56],['Daggdalen','elf',33,52],['Myrgläntan','elf',43,36],['Skogsmunte','elf',17,39],['Vattnaglod','human',59,72],['Glibra','human',47,53],['Gloume','human',58,54],['Hällsund','human',29,68],['Vindhult','human',39,62],['Skymningsvik','human',60,81],['Rimdal','dwarf',53,19],['Gråhammar','dwarf',74,22],['Stenport','dwarf',62,36],['Diacomb','dwarf',84,24],['Eldskreva','orc',81,57],['Askbranten','orc',82,68],['Korpudden','orc',71,67],['Tjärnäs','goblin',46,30],['Skrothåla','goblin',53,36],['Mossklyftan','troll',46,12],['Stendjup','troll',86,14]];
const BASE_PLACES=[...MAMBENNA_SETTLEMENTS.map((s,i)=>({...s,x:coords[i][0],y:coords[i][1]})),...extras.map(([name,race,x,y])=>({id:name.toLowerCase(),name,race,x,y,potential:12,description:race==='elf'?'En bosättning bland skogens höga träd.':race==='dwarf'?'Ett bergsfäste med djupa gruvgångar.':race==='orc'?'En befäst by vid kejsardömets gamla vägar.':'En liten bosättning i Mambenna.'}))];


export function nearbyPlaces(id:string){const origin=PLACES.find(p=>p.id===id);if(!origin)return [];const nearest=(p:typeof origin)=>PLACES.filter(q=>q.id!==p.id).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y)).slice(0,3);return PLACES.filter(p=>p.id!==id&&(nearest(origin).some(n=>n.id===p.id)||nearest(p).some(n=>n.id===id))).map(p=>({...p,days:Math.max(2,Math.ceil(Math.hypot(p.x-origin.x,p.y-origin.y)/5))}));}
export function divisionTown(name:string){if(name==='Kejsarserien')return 'Berunia';if(name.startsWith('Division 1'))return name.endsWith('Östra')?'Österborg':name.endsWith('Södra')?'Söderhamn':'Västerport';return name.replace(/^Division [23] /,'');}

const LOCAL_STORIES:Record<string,string>={
'Nätarhamn':'Nätarhamn är en dvärgby av låga stenhus, salta rökhus och grova bryggor vid sydkusten. Här arbetar nätbindare, fiskare, tunnmakare och hamnbärare sida vid sida innan gryningsskiftet går ut. Byns spelplan är byggd av packad strandsingel, och efter en hemmaseger slår arbetarna sina båtkrokar mot kajens järnringar tills ljudet hörs över hela viken.',
'Grotthem':'Grotthem är trollens största mötesplats, en stad av hallar i den östra kalkklippan. Eldar hålls brinnande vid varje port så att sena resenärer hittar hem. Vid den stora bollgården möts släkternas lag, och matchvinnaren får börja kvällens berättelse vid rådselden.',
'Dimmervad':'Dimmervads troll har byggt låga stenhus vid den norra flodens vadställe. I gryningen syns bara skorstenarna ovanför dimman. Här lär sig barnen fånga bollar från strand till strand, medan färjkarlarna envist hävdar att deras gamla rop gav upphov till spelets första laghejaramsor.',
'Rotdjup':'Rotdjup gömmer sig under väldiga rötter i den västra skogen. Trollfamiljerna odlar svamp och byter stenhuggararbete mot alvernas örter. Deras bollplan ligger i en naturlig sänka där publiken sitter på mjuka mossbankar och håller sig ovanligt tyst under uppkasten.',
'Kummelås':'Kummelås byggdes kring gravrösen från ett rike ingen längre minns. Trollens väktarsläkter sköter de gamla stigarna och tar emot resande med bröd bakat på heta hällar. På matchdag täcks rösena med färgade band; att kliva över dem på väg till planen anses ge svår otur.',
"Berunia":"Berunia reser sina vita murar över den skyddade bukten där rikets vägar slutar. Vid Gryningsporten vägs säd från Bortomgårda bredvid silver från dvärgarnas gruvor, och i trängseln hörs alla Mambennas språk. Kejsarens baner vajar över arenakvarteren; under dem ligger äldre bollgårdar där barn fortfarande spelar med hopbundna läderremsor. Stadens krönikörer hävdar att Yaraaz Vigil först fick gemensamma regler här. Hamnfolket svarar att hovet bara skrev ner vad alla redan kunde.",
"Tvillingstäderna":"Tvillingstäderna byggdes av två rivaliserande syskon på var sin flodstrand. Broarna som skulle förena dem blev snart marknadsplatser och omstridda spelplaner. Än i dag räknar invånarna noggrant vilken strand en manager föddes på. Inför stora matcher knyts blå band mellan broarnas räcken, och färjkarlarna tar betalt i förskott för att slippa jaga jublande resenärer.",
"Bortomgårda":"Bortomgårdas låga gårdar ligger bakom sädesfält och långa stengärden. Resande tror ofta att de kommit till en stillsam avkrok tills skördefesten börjar och hela trakten samlas kring bollplanen. De gamla spannmålsmagasinen tjänar som omklädningsrum. Här värderas uthållighet och ordhållighet högre än fina titlar, och en scout får gärna hjälpa till med lasset innan han börjar ställa frågor.",
"Hillgrunby":"Hillgrunbys kullar bär kvarnar, hästmarknader och den slingrande väg som köpmännen kallar Silvertråden. Varje kvarter har sin egen bollgård, men bara den vid brunnen anses riktigt plan. En gammal gränstvist avgjordes här genom en match som enligt byskrivaren varade tills båda lagen somnade. Det påståendet möts alltid av högljudda invändningar från grannbyn.",
"Skeppsvye":"Skeppsvye breder ut sig mellan saltmagasin, skeppsvarv och höga utkikstorn. Stormarna gör hamnen farlig men handeln rik, och varvsgillena har länge bekostat stadens spelplaner. På matchdag hissas lagens färger i masterna på de förtöjda skeppen. Den som lyssnar vid sjömanshärbärget får höra om främmande bollspel långt bortom Mambenna, fast berättelserna växer med varje stop.",
"Västlycke":"Västlycke ligger i lä bakom gröna åsar, med en veckomarknad som är äldre än kejsardömet. Byns ringklocka kallar både till handel och avkast, vilket ibland förvirrar nyanlända. Den lilla läktaren byggdes av spillvirke från en bröllopssal och har aldrig slutat dekoreras. Här känner alla någon som nästan blev en stor spelare, och ingen glömmer en scout som gick förbi.",
"Alymoon":"Alymoons bostäder följer grenarna i en skog vars äldsta träd saknar kända namn. Mellan trädkronorna går gångbroar som bara lyses upp när besökare väntas. Alvernas sångarkretsar bevarar berättelsen om den första boll som bars hit från människornas land. Många ogillade spelets oväsen; nu kan jublet höras över hela dalen när en av Alymoons söner eller döttrar lyckas i Kejsarspelen.",
"Skogskymning":"Skogskymning ligger där skogens mörka stigar öppnar sig mot betesmark. Jägare och budbärare förde bollspelet hit och tränade mellan de stora rötterna. På den gamla planen står ännu ett träd som ingen velat fälla, trots århundraden av klagomål från besökande spelare. Byborna dukar kvällsmat åt resande lag, men den som hånar skogen får själv hitta vägen hem.",
"Vemjelsen":"Vemjelsen speglar sig i en kall källsjö, omgiven av stenar ristade före kejsarnas tid. Här spelas vårens första match utan publikens trummor, så att sjöns väktare ska få sova vidare. De alviska familjerna vårdar gamla träkorgar som arvegods. Scouter söker sig hit för att se ungdomarna spela på strandens hala hällar, där ett oförsiktigt steg belönas med ett iskallt bad.",
"Larutappe":"Larutappes portar är uthuggna i en lodrät bergvägg. Innanför dem ligger verkstäder och bostäder kring ett schakt som skickar dagsljus ända ner till rådsalen. Stenhuggarna byggde stadens första arena för att avgöra vilken gruvgång som skulle få nya vagnar. Den tävlingen blev kvar långt efter att vagnarna rostat, och publiken markerar ännu varje periodseger med tre hammarslag.",
"Clamklyte":"Clamklytes hus står som hyllor längs bergets sida, sammanbundna av branta trappor och kedjebroar. Malmkaravanerna stannar här för att byta dragdjur och höra senaste nytt från rikets serier. Stadens spelare har en ovana att kalla varje plan utan lutning för bekväm. Under läktaren bevaras en sprucken stenboll som ingen nutida spelare har velat prova.",
"Nordstorme":"Nordstorme håller vakt där de sista odlingarna möter nordlandets snö. Dvärgarnas fästning har stått emot härar, köld och flera försök att flytta tullboden söderut. När vintervägen stängs blir bollmatcherna ortens stora samlingspunkt. Enligt tradition bär hemmalagets kapten en järnnyckel till planen, ett löfte om att portarna ska stå öppna för alla som trotsat resan.",
"Shraknek":"Shrakneks rökpelare syns långt innan dalens befästningar. Här samsas orcher från många klaner kring smedjor, boskapsfållor och en arena som byggts ut så ofta att ingen minns den första muren. Bollspelet gav klanerna ett sätt att mäta sig utan att ständigt bränna varandras förråd. Rivaliteten är fortfarande häftig, men värdshusen har fått betydligt fler hela tak.",
"Stormråde":"Stormrådes platå ligger öppen för vindar som kan välta ett tält på några ögonblick. Klanernas stensatta mötesplats blev med tiden en spelplan, och de låga murarna fungerar både som läktare och vindskydd. Resande domare brukar tilldelas den tyngsta manteln. Ortsborna säger att en välriktad passning här kräver lika mycket omdöme som styrka.",
"Stryxlya":"Stryxlyas skog döljer övergivna gränsvallar och orchsamhällen byggda kring gamla vakteldar. Här fann många fribrytare en plats att vila mellan uppdragen, och deras berättelser formade ortens bollspel. Byarnas lag möts på röjningar där rötterna gör varje löpning osäker. Den som söker en spelare behöver tålamod; i Stryxlya besvaras frågor först när kvällsmaten är delad.",
"Miltrand":"Miltrands röda klippor faller brant mot södra havet. Fiskare, sjökrigare och köpfolk delar stadens trånga hamn, medan klanernas fanor vajar ovanför den salta dimman. Bollplanerna anlades på gamla uppställningsplatser för skepp. En hemmaseger firas med horn från varje kaj, och även stadens grannar medger att Miltrand kan föra oväsen som en hel provins.",
 'Österborg':'Österborg vakar över vägen genom östra porten. Stadens blå fanor hänger mellan vakttornen, och bollspelarna övar kast mellan de gamla sköldställningarna.',
 'Söderhamn':'Söderhamns kajer doftar tjära och salt. Sjömännen fyllde de första läktarna här; än i dag slår hamnklockan när hemmalaget vinner en period.',
 'Västerport':'Karavanerna stannar i Västerport innan färden ut mot havet. Köpmannagillena tvistar om priser på dagen och delar samma läktare om kvällen.',
 'Björkebo':'Björkebo ligger kring en vitstammig lund som aldrig får huggas. Byborna bygger sina korgar av fallna grenar och välkomnar scouter med björksav och misstänksamma frågor.',
 'Kopparvik':'I Kopparvik färgar gruvdammet taken gröna. De äldsta spelarna var malmbärare, och en sprucken kopparkorg hänger ännu över tingshusets dörr.',
 'Rödmossen':'Rödmossens röda vatten sägs minnas en gammal här. Orcherna håller sina träningskamper på torra öar mellan tuvorna, långt från säkra vägar.',
 'Vassby':'Vassby är byggd på pålar vid en stilla sjö. Goblinernas smala båtar bär både fisk, post och nya bolltalanger mellan de gräsbevuxna stränderna.',
 'Tallås':'Tallås ligger högt bland raka furor. Vinterstormarna har lärt byns löpare att välja säkra steg och gömma ansiktet i kragen utan att tappa bollen.',
 'Silverlöv':'I Silverlöv skimrar träden blekt när dimman lägger sig. Byarnas vävare syr de silverkantade resmantlar som blivit traktens kännetecken.',
 'Mossvalla':'Mossvallas gamla träningsplan sjunker lite varje vår. Invånarna svarar med nya plankor, nya stigar och en sällsynt envishet inför varje bortamatch.',
 'Lövvik':'Lövvik är en liten lastplats där skogen möter vattnet. Här byter flodfolkets bollspelare berättelser med alviska jägare under hamnens lövtak.',
 'Daggdalen':'Daggdalen ligger dold i en mjuk sänka. Morgonernas hala gräs gör byns ungdomsmatcher till en prövning i både balans och tålamod.',
 'Myrgläntan':'Myrgläntans ljus syns sällan från landsvägen. Örtkunniga sköter små odlingar bakom husen och lyssnar på matchreferat vid den gemensamma elden.',
 'Skogsmunte':'Skogsmunte är känt för sina sångare och den årliga korgflätningen. En ny sidokorg välsignas av hela byn innan den får tas i bruk.',
 'Vattnaglod':'Vattnaglods kanaler delar staden i långa kvarter. Bollspelarna lärde sig tidigt att passa över broar där det inte fanns plats att springa förbi.',
 'Glibra':'Glibra växte kring en välbesökt vägkorsning. Värdshusens ägare tävlar om att hänga upp flest lagflaggor, men stadens egen fana sitter alltid högst.',
 'Gloume':'Gloumes låga torn står över fruktlundar och gamla tegelugnar. På matchdag säljs kryddbröd vid varje grind och torget töms tidigt.',
 'Hällsund':'Hällsund vaktar det smala sundet mellan två klippstränder. Besökande lag får vänja sig vid salt vind och en publik som överröstar måsarna.',
 'Vindhult':'I Vindhult står väderkvarnarna tätare än kyrktornen. När vinden vänder mitt under en match säger de gamla att kvarnmästaren har bytt lag.',
 'Skymningsvik':'Skymningsviks lanternor tänds innan solen når havet. Fiskarna kommer direkt från båtarna till matcherna med stövlarna ännu våta.',
 'Rimdal':'Rimdals broar täcks tidigt av frost. Dvärgarnas stenhuggare har ristat in byns första segrare i en pelare som står vid vintervägen.',
 'Gråhammar':'Gråhammars smedjor arbetar djupt inne i berget. De stora bälgarna tystnar bara under högtider och när ortens lag spelar hemma.',
 'Stenport':'Stenport ligger vid passets trängsta öppning. Här möts bergsfolkets olika stammar, och rivaliteten följer dem från handelstorget till planen.',
 'Diacomb':'Diacombs trappor leder ner till övergivna gruvsalar. En av salarna blev byns första arena; dess ekon gjorde även den minsta publik öronbedövande.',
 'Eldskreva':'Eldskrevas varma källor ryker mellan svarta stenar. Orcherna tränar i gryningen och söker skugga när hettan stiger över de spruckna åsarna.',
 'Askbranten':'Askbranten klamrar sig fast vid en mörk sluttning. Släktfanorna bär märken efter gamla stormar och tvättas aldrig inför en viktig match.',
 'Korpudden':'Korpudden är en vindpinad vaktby med utsikt över gränsleden. De svarta fåglarna följer lagen till planen i hopp om rester efter kvällsmaten.',
 'Tjärnäs':'Tjärnäs gömmer sina bryggor mellan vassruggar. Goblinernas nattmarknad lockar både fiskare, spelare och handlare som inte vill bli sedda på stora vägen.',
 'Skrothåla':'Skrothålas verkstäder är byggda av sådant andra har kastat bort. Byns gobliner skryter med att den första målburen bestod av tre grindar och ett stulet ankare.',
 'Mossklyftan':'Mossklyftans troll bor nära den gamla stenbron. De talar långsamt om släktens bragder, men rösterna blir betydligt starkare vid en jämn tvekamp.',
 'Stendjup':'Stendjup ligger där bergsvägen försvinner mellan höga väggar. Trollfamiljerna håller råd vid en rund sten och följer sina bollspelare som en enda stor släkt.'
};
export const PLACES=[...BASE_PLACES,{id:'nätarhamn',name:'Nätarhamn',race:'dwarf' as Race,x:64,y:89,potential:12,description:LOCAL_STORIES.Nätarhamn}].map(p=>({...p,description:LOCAL_STORIES[p.name]||p.description}));
