import {ArenaConfig,Club} from '../types';
const names=['Kejsararenan','Solkronan','Månporten','Drakvallen','Berunias borg','Silverläktaren','Örnnästet','Kronans gård','Rosentorget','Järnporten','Högvakten','Mitrilhallen','Vargborgen','Askfältet','Stormvallen','Kopparringen','Stjärnvalvet','Norrporten','Söderlyktan','Västervallen','Granitgården','Havsarenan','Gryningsvallen','Skymningsborg','Lövkransen','Flintgården','Korpnästet','Kungslunden','Tornringen','Mossvallen'];
// Kejsarens arenor är spridda över riket. Stora handelsorter har flera, medan mindre orter fortfarande får matchliv.
const imperialTowns=['Berunia','Berunia','Berunia','Berunia','Alymoon','Alymoon','Skeppsvye','Skeppsvye','Larutappe','Larutappe','Shraknek','Shraknek','Österborg','Österborg','Söderhamn','Söderhamn','Västerport','Västerport','Clamklyte','Hillgrunby','Miltrand','Tvillingstäderna','Skogskymning','Nordstorme','Stormråde','Vattnaglod','Glibra','Gloume','Skogsmunte','Västlycke'];
export const IMPERIAL_VENUES=names.map((name,i)=>({id:'imperial-'+i,name,hometown:imperialTowns[i],landscape:'Kejsardömets mark',underlag:(i===0?'Nimonimbus':['Gräs','Jord','Sten'][i%3]) as ArenaConfig['underlag'],capacity:i===0?120000:i<=10?30000:i<=20?40000:50000+(i-21)*5000,typeDescription:'Kejsarens arena',ara:i===0?20:1+i%8,skrack:i===0?20:(i*3)%9,cost:0,weeklyRent:0}));
export const CAPITAL_VENUES=[
 {id:'capital-alymoon',name:'Månkronans lund',ownerName:'Alymoons råd',hometown:'Alymoon',landscape:'Levande alvskog',underlag:'Gräs' as const,capacity:100000,typeDescription:'Alvernas huvudarena',ara:17,skrack:4,cost:0,weeklyRent:0},
 {id:'capital-skeppsvye',name:'Stormhamnens valv',ownerName:'Skeppsvyes råd',hometown:'Skeppsvye',landscape:'Örik hamnstad',underlag:'Nimonimbus' as const,capacity:100000,typeDescription:'Människornas huvudarena',ara:12,skrack:11,cost:0,weeklyRent:0},
 {id:'capital-larutappe',name:'Hammarsalen',ownerName:'Larutappes gillen',hometown:'Larutappe',landscape:'Bergshall',underlag:'Sten' as const,capacity:100000,typeDescription:'Dvärgarnas huvudarena',ara:12,skrack:12,cost:0,weeklyRent:0},
 {id:'capital-shraknek',name:'Klanernas käft',ownerName:'Shrakneks klanråd',hometown:'Shraknek',landscape:'Svart bergsdal',underlag:'Jord' as const,capacity:100000,typeDescription:'Orchernas huvudarena',ara:5,skrack:18,cost:0,weeklyRent:0},
];
export function standardVenue(f:{id:string}){const hash=[...f.id].reduce((a,c)=>a+c.charCodeAt(0),0);return {id:'standard-'+f.id,name:'Allmänna arenan '+(hash%900+100),landscape:'Allmän mark',underlag:['Gräs','Jord','Sten'][hash%3] as ArenaConfig['underlag'],capacity:30000,typeDescription:'Allmän matcharena',ara:hash%3,skrack:(hash+1)%3,cost:0,weeklyRent:0};}
export function bookingFee(v:any){return v.id?.startsWith('club-')&&Number.isInteger(v.rentalPrice)?v.rentalPrice:v.id?.startsWith('standard-')?0:Math.round((v.capacity*.2+(v.ara||0)**2*500+(v.skrack||0)**2*300)/100)*100}
export function venueCatalog(teams:any[]){return [...IMPERIAL_VENUES,...CAPITAL_VENUES,...teams.filter(c=>c.arena).map(c=>({...c.arena,id:'club-'+c.id,ownerName:c.name,hometown:c.hometown}))].map(v=>({...v,bookingFee:bookingFee(v)}))}
export function fixtureVenue(f:any,teams:any[]){return venueCatalog(teams).find(a=>a.id===(f.venueId||'club-'+f.homeId))||standardVenue(f)}
