import {useState} from 'react';
import {api} from '../lib/api';
import {useData,Message} from './WorldViews';
const labels:Record<string,string>={'club-name':'Ändra lagnamn','club-gold':'Justera lagkassan','account-ban':'Stäng av konto','account-unban':'Återaktivera konto','forum-hide':'Ta bort inlägg','forum-restore':'Återställ inlägg','forum-lock':'Lås tråd','forum-unlock':'Öppna tråd','chat-hide':'Ta bort chattmeddelande','auction-cancel':'Avbryt auktion','auction-edit':'Ändra auktion'};
export function Administration(){
 const {data,load,error}=useData('/administration',{clubs:[],accounts:[],auctions:[],forum:[],chat:[],audit:[]});
 const [tab,setTab]=useState('Lag'),[search,setSearch]=useState(''),[pending,setPending]=useState<any>(null),[reason,setReason]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const [clubId,setClubId]=useState(''),[name,setName]=useState(''),[shortName,setShortName]=useState(''),[amount,setAmount]=useState('');
 const [auctionId,setAuctionId]=useState(''),[price,setPrice]=useState(''),[endsAt,setEndsAt]=useState('');
 const team=data.clubs.find((c:any)=>c.id===clubId),auction=data.auctions.find((a:any)=>a.id===auctionId);
 const matches=(...parts:any[])=>parts.join(' ').toLocaleLowerCase('sv').includes(search.toLocaleLowerCase('sv'));
 const review=(action:string,target:any,subject:string,extra:any={})=>{setReason('');setPending({action,target,subject,...extra,requestId:crypto.randomUUID()});setStatus('');};
 return <section className="administration"><h2>Spelledning</h2><p>Ändringar gäller den riktiga spelvärlden. Alla åtgärder loggas med ditt namn, anledning och före/efter. Matchstart hanteras separat.</p><Message error={error}/><div className="tabs">{['Lag','Konton','Auktioner','Forum','Chatt','Ändringslogg'].map(t=><button key={t} aria-selected={t===tab} onClick={()=>{setTab(t);setSearch('')}}>{t}</button>)}</div><label>Sök i {tab.toLowerCase()} <input value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={load}>Uppdatera</button>
 {tab==='Lag'&&<><label>Lag<select value={clubId} onChange={e=>{setClubId(e.target.value);const c=data.clubs.find((c:any)=>c.id===e.target.value);setName(c?.name||'');setShortName(c?.shortName||'')}}><option value="">Välj lag</option>{data.clubs.filter((c:any)=>matches(c.name,c.ownerName,c.division)).map((c:any)=><option key={c.id} value={c.id}>{c.name} · {c.ownerName} · {c.division}</option>)}</select></label>{team&&<div className="notice"><p>{team.name} · Kassa: <b>{team.gold.toLocaleString('sv-SE')} guld</b></p><form onSubmit={e=>{e.preventDefault();review('club-name',team.id,team.name,{name,shortName})}}><label>Lagnamn<input required minLength={3} maxLength={50} value={name} onChange={e=>setName(e.target.value)}/></label><label>Kortnamn<input required maxLength={25} value={shortName} onChange={e=>setShortName(e.target.value)}/></label><button>Granska namnbyte</button></form><form onSubmit={e=>{e.preventDefault();review('club-gold',team.id,team.name,{amount:Number(amount)})}}><label>Guld att lägga till eller dra av<input type="number" required min={-10000000} max={10000000} step={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label><button>Granska kassajustering</button></form></div>}</>}
 {tab==='Konton'&&<table className="retro-table"><thead><tr><th>Manager / användarnamn</th><th>Lag</th><th>Status</th><th/></tr></thead><tbody>{data.accounts.filter((a:any)=>matches(a.managerName,a.name,a.clubName)).map((a:any)=><tr key={a.userId}><td>{a.managerName}<br/><small>{a.name}</small></td><td>{a.clubName}</td><td>{a.admin?'Administratör':a.banned?'Avstängd':'Aktiv'}</td><td>{!a.admin&&<button onClick={()=>review(a.banned?'account-unban':'account-ban',a.userId,a.managerName)}>{a.banned?'Återaktivera':'Stäng av'}</button>}</td></tr>)}</tbody></table>}
 {tab==='Auktioner'&&<><label>Pågående auktion<select value={auctionId} onChange={e=>{setAuctionId(e.target.value);const a=data.auctions.find((a:any)=>a.id===e.target.value);setPrice(String(a?.price||''));setEndsAt(a?new Date(+new Date(a.endsAt)-new Date(a.endsAt).getTimezoneOffset()*60000).toISOString().slice(0,16):'')}}><option value="">Välj auktion</option>{data.auctions.filter((a:any)=>matches(a.name,a.sellerName,a.bidderName)).map((a:any)=><option key={a.id} value={a.id}>{a.name} · {a.sellerName} · {a.price} guld</option>)}</select></label>{auction&&<div className="notice"><p>{auction.name} · Säljare: {auction.sellerName}<br/>Högsta bud: {auction.price} guld · {auction.bidderName}</p><form onSubmit={e=>{e.preventDefault();review('auction-edit',auction.id,auction.name,{kind:auction.kind,price:Number(price),endsAt:new Date(endsAt).toISOString()})}}><label>{auction.bidderId?'Högsta bud (låst)':'Utgångspris'}<input type="number" min={1} max={100000000} required disabled={!!auction.bidderId} value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Sluttid (din lokala tid)<input type="datetime-local" required value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label><button>Granska auktionsändring</button></form><button onClick={()=>review('auction-cancel',auction.id,auction.name,{kind:auction.kind})}>Avbryt auktion…</button><p>Vid avbrott behåller säljaren tillgången. Eventuella äldre reserverade bud återbetalas. Avslutade köp ändras inte här.</p></div>}</>}
 {tab==='Forum'&&<><p>De 500 senaste inläggen. Borttagna inlägg kan återställas.</p><table className="retro-table"><thead><tr><th>Inlägg</th><th>Författare</th><th>Moderera</th></tr></thead><tbody>{data.forum.filter((p:any)=>matches(p.title,p.text,p.author)).map((p:any)=><tr key={p.id}><td><b>{p.title}</b><p>{p.text}</p><small>{p.category} · {new Date(p.date).toLocaleString('sv-SE')}{p.locked?' · Låst':''}</small></td><td>{p.author}</td><td><button onClick={()=>review(p.removed?'forum-restore':'forum-hide',p.id,p.title)}>{p.removed?'Återställ':'Ta bort'}</button>{!p.threadId&&!p.removed&&<button onClick={()=>review(p.locked?'forum-unlock':'forum-lock',p.id,p.title)}>{p.locked?'Öppna':'Lås tråd'}</button>}</td></tr>)}</tbody></table></>}
 {tab==='Chatt'&&<table className="retro-table"><thead><tr><th>Avsändare</th><th>Meddelande</th><th/></tr></thead><tbody>{data.chat.filter((p:any)=>matches(p.authorName,p.content)).map((p:any)=><tr key={p.id}><td>{p.authorName}</td><td>{p.content}</td><td><button onClick={()=>review('chat-hide',p.id,p.authorName+': '+p.content.slice(0,100))}>Ta bort</button></td></tr>)}</tbody></table>}
 {tab==='Ändringslogg'&&<><p>De 100 senaste åtgärderna.</p>{data.audit.filter((a:any)=>matches(a.reason,a.actorName,a.action,a.target)).map((a:any)=><details className="notice" key={a.id}><summary>{new Date(a.date).toLocaleString('sv-SE')} · {labels[a.action]||a.action} · {a.actorName}</summary><p>{a.reason}</p><p>Mål: {a.target}</p><b>Före</b><pre>{JSON.stringify(a.before,null,2)}</pre><b>Efter</b><pre>{JSON.stringify(a.after,null,2)}</pre></details>)}</>}
 <p role="status">{status}</p>{pending&&<div className="admin-review" role="dialog" aria-modal="true" aria-labelledby="admin-review-title"><form className="notice" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);try{await api('/administration/action',{...pending,reason});setPending(null);setStatus('Ändringen är sparad och loggad.');load()}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}}><h3 id="admin-review-title">{labels[pending.action]}</h3><p>{pending.subject}</p>{pending.name&&<p>Nytt namn: {pending.name} · {pending.shortName}</p>}{pending.amount!==undefined&&<p>Förändring: {pending.amount.toLocaleString('sv-SE')} guld</p>}{pending.endsAt&&<p>Pris: {pending.price} · Slutar: {new Date(pending.endsAt).toLocaleString('sv-SE')}</p>}<label>Anledning (sparas i loggen)<textarea autoFocus minLength={5} maxLength={500} required value={reason} onChange={e=>setReason(e.target.value)}/></label><p role="alert">{status}</p><button disabled={busy||reason.trim().length<5}>{busy?'Sparar…':'Bekräfta åtgärden'}</button><button type="button" disabled={busy} onClick={()=>setPending(null)}>Avbryt</button></form></div>}
 </section>;
}
