import {useHistoryState} from '../lib/useHistoryState';
import {PlayersListView} from './PlayersListView';
import {TeamPlayersStatistics,Guestbook} from './ProfileSections';
import {TransferHistory} from './CommunityViews';import {EntityLink,PlaceLink} from './EntityLink';
import {ClubExtras,ClubSettings} from './ProgressionViews';
import {ClubStatistics} from './FeatureViews';
import {useState} from 'react';import {Club,Player} from '../types';import {RACE_DISPLAY_NAMES} from '../constants/attributes';import {Crest} from './Crest';
export function ClubView({club,players,onNavigateTab,onUpdatePresentation,readOnly=false,onPlayer}: {club:Club;players:Player[];readOnly?:boolean;onPlayer?:(id:number)=>void;onNavigateTab:(s:string)=>void;onUpdatePresentation:(s:string)=>void;onSimulateQuickMatch?:()=>void}){
 const [detailTab,setDetailTab]=useHistoryState('ClubView:1',"Lagstatistik");
 const [edit,setEdit]=useHistoryState('ClubView:2',false),[text,setText]=useHistoryState('ClubView:3',club.presentation);
 return <section><div className="club-heading"><Crest race={club.race}/><h2>{club.name}</h2></div>{(club as any).bankruptcy&&<aside role="status" className="bankruptcy-notice" style={{border:'2px solid #843c31',padding:16,background:'#f0dfcf',margin:'16px 0'}}><h3>Laget är försatt i konkurs</h3><p>{(club as any).bankruptcy.reason}. Konkursförvaltaren har tagit över klubben.</p><small>{new Date((club as any).bankruptcy.date).toLocaleDateString('sv-SE')}</small></aside>}<ClubExtras clubId={club.id}/><div className="presentation"><b>Presentation:</b>{!readOnly&&<button className="text-link" onClick={()=>{setText(club.presentation);setEdit(!edit)}}>{edit?'Avbryt':'Redigera'}</button>}{edit?<div><textarea aria-label="Presentation" value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>{onUpdatePresentation(text);setEdit(false)}}>Spara</button></div>:<p>{club.presentation}</p>}</div><div className="club-details"><table className="retro-table"><thead><tr><th colSpan={2}>LagDetaljer</th></tr></thead><tbody>{[['LagID',club.id],['Kort lagnamn',club.shortName],['Serie',club.division],['Serieposition',club.position],['Hemort',<PlaceLink name={club.hometown}/>],['Moral',((club as any).morale??100)+' %'],['Merit',club.merit],['Matcher',club.recordString],['Ras',RACE_DISPLAY_NAMES[club.race]],['Arena',club.arena?<EntityLink kind="venue" id={'club-'+club.id}>{club.arena.name}</EntityLink>:'Ingen'],['Tränare',club.coach?.name||'Ingen'],['Spelare',players.length]].map(([k,v])=><tr key={String(k)}><th>{k}</th><td>{!readOnly&&['Serie','Spelare'].includes(String(k))?<button className="text-link" onClick={()=>onNavigateTab(k==='Serie'?'division':k==='Arena'?'arena':'spelare')}>{v}</button>:v}</td></tr>)}</tbody></table><table className="retro-table owner-info"><thead><tr><th colSpan={2}>ÄgarInfo</th></tr></thead><tbody><tr><th>Ägare</th><td>Anonym</td></tr><tr><th>Manager</th><td>{club.ownerName}</td></tr><tr><th>Email</th><td>Anonym</td></tr><tr><td colSpan={2} className="online">{readOnly?(club.isBot?"Datorlag":"Manager"):club.ownerName+" är inloggad!"}</td></tr></tbody></table></div><div className="tabs">{['Lagstatistik','Spelarstatistik','Transfers'].map(t=><button key={t} aria-selected={detailTab===t} onClick={()=>setDetailTab(t)}>{t}</button>)}</div>{detailTab==='Lagstatistik'?<ClubStatistics clubId={club.id}/>:detailTab==='Transfers'?<TransferHistory clubId={club.id}/>:<TeamPlayersStatistics clubId={club.id}/>}<details className="club-roster"><summary>Spelartrupp ({players.length})</summary><PlayersListView players={players}/></details><Guestbook clubId={club.id}/>{readOnly&&!club.isBot&&localStorage.getItem("arena_guest")!=="true"&&<EntityLink kind="mail" id={club.id}>✉ Skicka brev till managern</EntityLink>}{!readOnly&&<ClubSettings club={club} onRefresh={()=>location.reload()}/>}</section>;
}

