import {InjuryMark} from './InjuryMark';
import {cleanLineup} from '../engine/cleanLineup';
import {RaceIcon} from './RaceIcon';
import {effectiveAttributes} from '../constants/market';
import {RACE_DISPLAY_NAMES} from '../constants/attributes';
import {useData} from './WorldViews';
import {api} from '../lib/api';
import {calculatePlayerPositionRatings} from '../engine/positionRatings';
import {PositionPreview} from './PositionPreview';
import {useState} from 'react';
import {Club,Player,LineupConfig} from '../types';
import {SLOT_KEYS,activeIds,reserveIds,validateLineup} from '../engine/lineup';
import {Meter} from './SquadOverview';
import {ATTRIBUTE_NAMES_SV} from '../constants/attributes';
const labels=['Ytteranfall','Anfall','Ytteranfall','Yttermittfält','Innermittfält','Yttermittfält','Ytterback','Back','Ytterback','Mål'];
export function LineupView({club,players,onSaveLineup,canManageVenue=true}:{club:Club;players:Player[];onSaveLineup:(l:LineupConfig)=>Promise<void>;canManageVenue?:boolean;onSelectPlayer?:(id:number)=>void;onSimulateMatch?:()=>void}){
 const {data:presets,load:reloadPresets}=useData('/lineup-presets/'+club.id);
 const [tapPlacement,setTapPlacement]=useState(()=>typeof window!=='undefined'&&window.matchMedia('(pointer: coarse)').matches);
 const [presetSlot,setPresetSlot]=useState(0),[presetName,setPresetName]=useState(''),[ratingSlot,setRatingSlot]=useState<string|null>(null);
 const [hovered,setHovered]=useState<Player|null>(null),[selected,setSelected]=useState<number|null>(null),[dragged,setDragged]=useState<number|null>(null);
 const [lineup,setLineup]=useState<LineupConfig>(()=>cleanLineup(club.lineup,players)),[mode,setMode]=useState('Spelare'),[message,setMessage]=useState(''),[error,setError]=useState('');
 const active=new Set(SLOT_KEYS.flatMap(k=>activeIds(lineup.slots[k])).filter(id=>players.some(p=>p.id===id&&!p.isDeceased)));const preview=hovered||players.find(p=>p.id===selected);
 const jersey=(p:Player)=>{if(!ratingSlot)return p.shirtNumber;const r=p.positionRatingsWithForm||calculatePlayerPositionRatings(p,true);return ratingSlot==='goal'?r.goalBox:r.matrix[+ratingSlot[0]][+ratingSlot[2]];};
 const place=(key:string,id:number)=>{const p=players.find(p=>p.id===id);if(!p||p.isDeceased){setError('Spelaren är inte spelklar.');return}
  if(mode==='Reserver'&&active.has(id)){setError('Ta först bort spelaren från den aktiva uppställningen.');return}
  const field=mode==='Spelare'?'activePlayerIds':'reservePlayerIds';const copy=structuredClone(lineup);
  for(const k of SLOT_KEYS){const v=copy.slots[k];copy.slots[k]={slotKey:k,starterPlayerId:null,subPlayerId:null,activePlayerIds:activeIds(v).filter(n=>mode!=='Spelare'||n!==id),reservePlayerIds:reserveIds(v).filter(n=>mode!=='Spelare'||n!==id)};}
  const target=copy.slots[key][field]||[];if(target.includes(id))return;if(target.length>=2){setError('Rutan har redan två spelare.');return}
  if(mode==='Spelare'&&!active.has(id)&&active.size>=10){setError('Högst tio aktiva. Dra först en spelare tillbaka till bänken.');return}
  copy.slots[key][field]=[...target,id];setLineup(copy);setSelected(id);setError('');setMessage(p.name+' är placerad.');setDragged(null);
 };
 const remove=(id:number,key?:string)=>{const copy=structuredClone(lineup);for(const k of SLOT_KEYS){const v=copy.slots[k];if(key&&key!==k)continue;copy.slots[k]={slotKey:k,starterPlayerId:null,subPlayerId:null,activePlayerIds:activeIds(v).filter(n=>n!==id),reservePlayerIds:reserveIds(v).filter(n=>n!==id)}}setLineup(copy);setDragged(null);setMessage('');};
 const shirt=(p:Player,_slot?:string,_index?:number)=><button key={p.id} draggable={!p.isDeceased} className={'shirt '+(p.currentInjury?'injured ':'')+(selected===p.id?'selected ':'')+(p.isMercenary?'mercenary':'')} onDragStart={e=>{e.dataTransfer.setData('text/plain',String(p.id));setDragged(p.id);setSelected(p.id)}} onDragEnd={()=>setDragged(null)} onClick={e=>{e.stopPropagation();setSelected(p.id);setHovered(null)}} onMouseEnter={()=>setHovered(p)} onMouseLeave={()=>setHovered(null)} onFocus={()=>setSelected(p.id)} title={p.name} aria-label={'Visa '+p.name+', nummer '+p.shirtNumber}><RaceIcon race={p.race}/>{p.isDeceased?'†':jersey(p)}{p.isMercenary&&<span className="mercenary-star" aria-label="Fribrytare">★</span>}{p.currentInjury>0&&<InjuryMark value={p.currentInjury}/>}</button>;
 return <section className="formation-page"><h2>Uppställning</h2><p>Arena: {club.arena?.name||'Bestäms i matchplaneringen'}</p><div className="lineup-board"><div className="tabs">{['Spelare','Reserver'].map(t=><button key={t} aria-selected={mode===t} onClick={()=>setMode(t)}>{t}</button>)}</div>
 <div className="placement-toolbar"><button aria-pressed={tapPlacement} onClick={()=>setTapPlacement(!tapPlacement)}>{tapPlacement?"Markera och placera: på":"Markera och placera"}</button>{tapPlacement&&<span role="status">{selected?"Tryck på rutan där spelaren ska stå.":"1. Tryck på en tröja. 2. Tryck på en ruta."}</span>}{selected&&<button onClick={()=>{remove(selected);setSelected(null)}}>Flytta vald spelare till bänken</button>}</div><div className="lineup-layout"><div className={'pitch surface-'+((club.arena?.underlag==='Nimonimbus'?lineup.underlag:club.arena?.underlag)||lineup.underlag)}>{SLOT_KEYS.map((key,i)=><div key={key} className={'pitch-cell '+(key==='goal'?'goal ':'')+(tapPlacement&&selected?'tap-target':'')} tabIndex={tapPlacement?0:-1} onClick={()=>{if(tapPlacement&&selected)place(key,selected)}} onKeyDown={e=>{if(tapPlacement&&selected&&(e.key==='Enter'||e.key===' ')){e.preventDefault();place(key,selected)}}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=Number(e.dataTransfer.getData('text/plain'));if(id)place(key,id)}} onPointerDown={e=>{if(e.target===e.currentTarget){e.currentTarget.setPointerCapture(e.pointerId);setRatingSlot(key)}}} onPointerUp={()=>setRatingSlot(null)} onPointerCancel={()=>setRatingSlot(null)} role="group" aria-label={labels[i]+' '+key}><span className="cell-label">{labels[i]}</span>{(mode==='Spelare'?activeIds(lineup.slots[key]):reserveIds(lineup.slots[key])).map((id,n)=>{const p=players.find(p=>p.id===id);return p?<span className="field-player" key={id}>{shirt(p,key,n)}<button className="remove-shirt" title="Ta bort från rutan" aria-label={'Ta bort '+p.name+' från '+key} onClick={e=>{e.stopPropagation();remove(id,key)}}>×</button></span>:null})}</div>)}</div>
 <div className={'bench '+(dragged?'drop-ready':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();remove(Number(e.dataTransfer.getData('text/plain')))}} aria-label="Spelarbänk">{players.filter(p=>!active.has(p.id)).map(p=>shirt(p))}</div></div>
 <p className="compact">Klicka på en tröja för att granska. Dra till en ruta för att placera, eller till bänken för att ta bort. Håll nere på rutans bakgrund för positionspoäng med form.</p>
 <div className="formation-lower"><div className="formation-player"><h3 className="section-bar">{preview?preview.shirtNumber+'. '+preview.name+' · '+RACE_DISPLAY_NAMES[preview.race]:'Spelaregenskaper'}</h3>{preview?<div className="formation-preview"><table className="retro-table compact"><tbody>{Object.entries(ATTRIBUTE_NAMES_SV).map(([k,n])=><tr key={k}><th>{n}</th><td><Meter value={(effectiveAttributes(preview) as any)[k]}/></td></tr>)}</tbody></table><PositionPreview player={preview}/></div>:<p>Klicka eller peka på en spelare.</p>}</div>
 <div className="formation-controls"><p><b>{active.size}/10 aktiva</b>{mode==='Reserver'&&' · Reserv 1 går in före reserv 2. Samma reserv får täcka flera rutor.'}</p><div className="form-row">{canManageVenue&&<label>Inträde <input aria-label="Inträde" type="number" min={0} max={100} value={lineup.intrade} onChange={e=>setLineup({...lineup,intrade:+e.target.value})}/></label>}<label>Underlag {canManageVenue&&club.arena?.underlag==='Nimonimbus'?<select value={lineup.underlag} onChange={e=>setLineup({...lineup,underlag:e.target.value as any})}>{['Gräs','Jord','Sten'].map(v=><option key={v}>{v}</option>)}</select>:<b>{club.arena?.underlag||'Matcharenans'}</b>}</label></div>
 {([['uppspel','Uppspel',['Normal','Passning','Löpning']],['spelvag','Spelväg',['Normal','Kant','Mitten']],['skytte','Skytte',['Normal','Korg','Mål']]] as any[]).map(([key,label,options])=><label className="tactic-control" key={key}>{label}<select value={(lineup.tactics as any)[key]} onChange={e=>setLineup({...lineup,tactics:{...lineup.tactics,[key]:e.target.value}})}>{options.map((v:string)=><option key={v}>{v}</option>)}</select></label>)}
 <div className="preset-controls"><h3 className="section-bar">Standarduppställning</h3><select aria-label="Standardplats" value={presetSlot} onChange={e=>{setPresetSlot(+e.target.value);setPresetName(presets[+e.target.value]?.name||'')}}>{[0,1,2].map(i=><option key={i} value={i}>{i+1}. {presets[i]?.name||'Tom'}</option>)}</select><button disabled={!presets[presetSlot]} onClick={()=>setLineup(cleanLineup(presets[presetSlot].lineup,players))}>Läs in</button><input aria-label="Standardnamn" placeholder="Namn" maxLength={40} value={presetName} onChange={e=>setPresetName(e.target.value)}/><button onClick={async()=>{try{await api('/lineup-presets/'+club.id,{slot:presetSlot,name:presetName,lineup});reloadPresets();setMessage('Standarduppställningen är sparad.');setError('')}catch(e:any){setError(e.message)}}}>Spara standard</button></div>
 <button className="save-lineup" onClick={async()=>{const invalid=validateLineup(lineup,players);if(invalid){setError(invalid);return}try{await onSaveLineup(lineup);setError('');setMessage('Uppställningen är sparad.')}catch(e:any){setError(e.message)}}}>Spara uppställning</button></div></div><p role="status">{message}</p>{error&&<p className="error">{error}</p>}</div></section>;
}
