import {useHistoryState} from '../lib/useHistoryState';
import {PlayerStatisticsTable} from './PlayerStatisticsTable';
import {RACE_DISPLAY_NAMES} from '../constants/attributes';
import {useState} from 'react';import {useData,Message} from './WorldViews';import {api} from '../lib/api';import {EntityLink} from './EntityLink';
export function TeamPlayersStatistics({clubId}:{clubId:string}){const [season,setSeason]=useHistoryState('ProfileSections:1','total'),{data,error}=useData('/club-player-statistics/'+clubId+'?season='+season,{seasons:[],players:[]});return <section><h3>Spelarstatistik</h3><label>Säsong <select value={season} onChange={e=>setSeason(e.target.value)}><option value="total">Totalt</option>{data.seasons.map((s:number)=><option key={s} value={s}>{s}</option>)}</select></label><Message error={error}/><PlayerStatisticsTable players={data.players}/></section>}
export function Guestbook({clubId}:{clubId:string}){const {data,load,error}=useData('/guestbook/'+clubId),[text,setText]=useHistoryState('ProfileSections:2',''),[status,setStatus]=useHistoryState('ProfileSections:3','');return <section className="guestbook"><h3 className="section-bar">Gästbok</h3><Message error={error}/>{data.map((p:any)=><article className="guestbook-entry" key={p.id}><b><EntityLink kind="club" id={p.clubId}>{p.clubName}</EntityLink> · {p.author}</b><small>{new Date(p.date).toLocaleString('sv-SE')}</small><p>{p.text}</p></article>)}{!data.length&&<p>Ingen har lämnat en hälsning ännu.</p>}{localStorage.getItem('arena_guest')!=='true'&&<form onSubmit={async e=>{e.preventDefault();try{await api('/guestbook/'+clubId,{text});setText('');load();setStatus('Hälsningen är sparad.')}catch(e:any){setStatus(e.message)}}}><label>Din hälsning<textarea required maxLength={2000} value={text} onChange={e=>setText(e.target.value)}/></label><button>Skriv i gästboken</button></form>}<p role="status">{status}</p></section>}
export function HistoricalPlayerStats({id}:{id:number}){const [season,setSeason]=useHistoryState('ProfileSections:4','total'),{data,error}=useData('/player-statistics/'+id+'?season='+season,{seasons:[],player:{stats:{}}});return <section><h3 className="section-bar">Spelarstatistik</h3><label>Säsong <select value={season} onChange={e=>setSeason(e.target.value)}><option value="total">Totalt</option>{data.seasons.map((s:number)=><option value={s} key={s}>{s}</option>)}</select></label><Message error={error}/><p>Representerade lag: {data.player.clubs?.map((c:any,i:number)=><span key={c.id}>{i>0?" / ":""}<EntityLink kind="club" id={c.id}>{c.name}</EntityLink></span>)}</p><p>Matcher: {data.player.matches||0} · Assist: {data.player.assists||0}</p><table className="retro-table"><thead><tr><th>Gren</th><th>Totalt</th><th>Lyckade</th><th>Viktat</th></tr></thead><tbody>{[['lopningar','Löpningar'],['passningar','Passningar'],['mottagningar','Mottagningar'],['skott','Skott / mål'],['korgskott','Korgskott / korgmål'],['slagsmal','Slagsmål'],['uppkast','Uppkast'],['raddningar','Räddningar'],['korgraddningar','Korgräddningar']].map(([k,n])=><tr key={k}><th>{n}</th><td>{data.player.stats[k]?.antal||0}</td><td>{data.player.stats[k]?.lyckade||0}</td><td>{data.player.weightedMatches?Math.round(data.player.stats[k]?.viktat||0):'–'}</td></tr>)}</tbody></table></section>}
export function TipsHistory({clubId}:{clubId:string}){const {data,error}=useData('/tips-history/'+clubId);return <section><h3>Tidigare tipsomgångar</h3><Message error={error}/>{data.map((r:any)=><details key={r.id}><summary>Omgång {r.round} · {r.games.filter((g:any)=>g.result&&g.pick===g.result).length} rätt · Vinst {r.award||0} guld</summary><table className="retro-table"><thead><tr><th>Match</th><th>Resultat</th><th>Ditt tips</th></tr></thead><tbody>{r.games.map((g:any)=><tr key={g.id}><td><EntityLink kind="club" id={g.homeId}>{g.homeName}</EntityLink> – <EntityLink kind="club" id={g.awayId}>{g.awayName}</EntityLink></td><td>{g.played?g.homeScore+'–'+g.awayScore+' ('+g.result+')':'Inte spelad'}</td><td>{g.pick||'–'}{g.result&&g.result===g.pick?' ✓':''}</td></tr>)}</tbody></table></details>)}{!data.length&&<p>Inga sparade tips ännu.</p>}</section>}

export function TipsStandings(){const [season,setSeason]=useHistoryState('ProfileSections:5','total'),{data,error}=useData('/tips-results?season='+season,{seasons:[],rounds:[],top:[]});return <section><h3>Tipsets topplista</h3><select aria-label="Tipsets säsong" value={season} onChange={e=>setSeason(e.target.value)}><option value="total">Totalt</option>{data.seasons.map((s:number)=><option value={s} key={s}>Säsong {s}</option>)}</select><Message error={error}/><table className="retro-table"><thead><tr><th>Lag</th><th>Poäng</th><th>Omgångar</th><th>Omgångssegrar</th></tr></thead><tbody>{data.top.map((r:any)=><tr key={r.id}><td><EntityLink kind="club" id={r.id}>{r.name}</EntityLink></td><td>{r.points}</td><td>{r.rounds}</td><td>{r.wins}</td></tr>)}</tbody></table><h3>Omgångarnas vinnare</h3>{data.rounds.filter((r:any)=>season==='total'||r.season===+season).map((r:any)=><article key={r.id}><h4>Säsong {r.season} · Omgång {r.round}</h4><p>{r.winners.length?r.winners.map((w:any)=><span key={w.id}><EntityLink kind="club" id={w.id}>{w.name}</EntityLink> </span>):'Ingen inlämnad kupong.'} · {r.points} rätt · Pott {r.pot.toLocaleString('sv-SE')} guld</p></article>)}{!data.rounds.length&&<p>Ingen tipsomgång är färdigspelad ännu.</p>}</section>}
