import {WeatherBox} from './ProgressionViews';
import {LoreBox} from './LoreBox';
import {Entity} from './FeatureViews';
import React, {useState,useEffect,useRef} from 'react';
import {Club} from '../types';
interface Props {onOpen?:(e:Entity)=>void;onMatch?:(id:string)=>void;club:Club;currentTab:string;onSelectTab:(t:string)=>void;onOpenNewClub:()=>void;shoutboxMessages:Array<{user:string;time:string;text:string}>;onAddShout:(t:string)=>Promise<void>;children:React.ReactNode}
export function RetroFrame(p:Props){
 const [admin,setAdmin]=useState(false);useEffect(()=>{fetch('/api/auth/status').then(r=>r.json()).then(d=>setAdmin(d.user?.admin===true)).catch(()=>{});},[]);
 const [menuOpen,setMenuOpen]=useState(false),[chatOpen,setChatOpen]=useState(false),[chatError,setChatError]=useState(''),[sending,setSending]=useState(false);
 const [onlineOpen,setOnlineOpen]=useState(false),[online,setOnline]=useState<any[]>([]);const chatRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(chatRef.current)chatRef.current.scrollTop=chatRef.current.scrollHeight},[p.shoutboxMessages.length,chatOpen]);
 const toggleOnline=async()=>{const open=!onlineOpen;setOnlineOpen(open);if(open)try{const r=await fetch('/api/online');setOnline(r.ok?await r.json():[])}catch{setOnline([])}};
 const [news,setNews]=useState(0);useEffect(()=>{const load=()=>fetch('/api/team-news/'+p.club.id).then(r=>r.ok?r.json():[]).then(d=>setNews(d.filter((n:any)=>!n.read).length)).catch(()=>{});load();const timer=setInterval(load,15000);window.addEventListener('arena-news-read',load);return()=>{clearInterval(timer);window.removeEventListener('arena-news-read',load)}},[p.club.id]);
 const [text,setText]=useState(''),[unread,setUnread]=useState(0);useEffect(()=>{const load=()=>fetch('/api/mail-unread').then(r=>r.json()).then(d=>setUnread(d.count||0)).catch(()=>{});load();const timer=setInterval(load,15000);window.addEventListener('arena-mail-read',load);return()=>{clearInterval(timer);window.removeEventListener('arena-mail-read',load)}},[]);
 const links=[['nyheter','Nyheter'],['serier','Serier'],['varlden','Världen'],['sok','Sök'],['transfer','Transfer'],['tipset','Tipset'],['forum','Forum'],['statistik','Statistik'],['regler','Regler'],['kontakta','Kontakta SL']];
 const own=[['lag',p.club.shortName||'Mitt lag'],['ekonomi','Ekonomi'],['division',p.club.division],['spelare','Spelare'],['uppstallning','Uppställning'],['matcher','Matcher'],['bud','Bud'],['magi','Magi'],['lakare','Läkare'],['artefakter','Artefakter'],['traning','Träning'],['talangjakt','Talangjakt'],['arena','Arena'],['post','Post']];
 const nav=(items:string[][])=>items.map(([id,label])=><button key={id} className={(p.currentTab===id?'current ':'')+((id==='post'&&unread)||(id==='nyheter'&&news)?'unread-post':'')} onClick={()=>{p.onSelectTab(id);setMenuOpen(false)}}>{id==='post'&&unread?'✉ '+label+' ('+unread+')':label}</button>);
 return <div className={'arena-shell race-'+p.club.race}><header className="masthead"><button className="wordmark" onClick={()=>p.onSelectTab('lag')}>ARENA</button><LoreBox onOpen={p.onOpen} onMatch={p.onMatch}/></header><div className="stone-horizontal"/><div className="mobile-toolbar"><button aria-expanded={menuOpen} onClick={()=>{setMenuOpen(!menuOpen);setChatOpen(false)}}>☰ Meny</button><span>{[...links,...own].find(([id])=>id===p.currentTab)?.[1]||"Arena"}</span><button aria-expanded={chatOpen} onClick={()=>{setChatOpen(!chatOpen);setMenuOpen(false)}}>Chatt</button></div><div className="arena-columns"><nav className={"left-nav "+(menuOpen?"mobile-open":"")}>{nav(links)}<button className="guide" onClick={()=>{p.onSelectTab('guide');setMenuOpen(false)}}>Nybörjarguide</button><hr/>{nav(own)}{admin&&<button onClick={()=>{p.onSelectTab('administration');setMenuOpen(false)}}>⚙ Administration</button>}<hr/><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()}}>Logga ut</button></nav><main className="game-page">{p.children}</main><aside className={"community "+(chatOpen?"mobile-open":"")}><button className="chat-heading" aria-expanded={onlineOpen} onClick={toggleOnline}>Gemensam chatt · {p.club.ownerName}</button>{onlineOpen&&<div className="online-list"><b>Online nu</b>{online.length?online.map(u=><span key={u.userId}>● {u.name}</span>):<span>Ingen annan syns online.</span>}</div>}<p className="muted">Chatten börjar om varje måndag 04.00, svensk tid.</p><div className="chat-messages" ref={chatRef}>{p.shoutboxMessages.length===0?<p className="muted">Inga meddelanden ännu.</p>:p.shoutboxMessages.map((m,i)=><div key={i}><b>{m.user} {m.time}</b><br/>{m.text}</div>)}</div><form onSubmit={async e=>{e.preventDefault();if(!text.trim()||sending)return;setSending(true);setChatError('');try{await p.onAddShout(text);setText('')}catch(e:any){setChatError(e.message)}finally{setSending(false)}}}><input aria-label="Chattmeddelande" value={text} onChange={e=>setText(e.target.value)} maxLength={500}/><button type="submit" disabled={sending||!text.trim()}>{sending?"Skickar…":"Skicka"}</button></form>{chatError&&<p className="error" role="alert">{chatError}</p>}<WeatherBox place={p.club.hometown}/><div className="world-clock">Matcher: tis / fre 19.00<br/>Träning: söndag 06.00<br/><small>Svensk tid</small></div></aside></div></div>;
}

