import {useHistoryState} from '../lib/useHistoryState';
import {EntityLink} from './EntityLink';
import {Statistics} from './StatisticsPage';
import {ImperialGamesView} from './ImperialGamesView';
import {Entity} from './FeatureViews';
import {DivisionTree} from './DivisionTree';
import {useState} from 'react';import {Club} from '../types';import {DIVISION_NAMES} from '../constants/leagues';import {useData,Message,Forum} from './WorldViews';import {Crest} from './Crest';
export function FixtureList({fixtures,onMatch}:{fixtures:any[];onMatch?:(id:string)=>void}){return <>{Array.from(new Set(fixtures.map(f=>f.round))).map(round=><div className="fixture-round" key={round}><h3>Omgång {round} · {new Date(fixtures.find(f=>f.round===round).date).toLocaleString('sv-SE',{timeZone:'Europe/Stockholm',dateStyle:'short',timeStyle:'short'})}</h3>{fixtures.filter(f=>f.round===round).map(f=><div className="fixture-row" key={f.id}><div><EntityLink kind="club" id={f.homeId}>{f.homeName}</EntityLink> – <EntityLink kind="club" id={f.awayId}>{f.awayName}</EntityLink> <button className="text-link" onClick={()=>onMatch?.(f.id)}>Match →</button></div><span>{f.played?f.homeScore+' – '+f.awayScore:'–'}</span></div>)}</div>)}{!fixtures.length&&<p className="empty">Inga matcher att visa.</p>}</>}
export function SeriesView({userClub,initialDivision,onMatch,onClub}:{userClub:Club;initialDivision?:string;onMatch:(id:string)=>void;onClub:(id:string)=>void}){const [division,setDivision]=useHistoryState('SeriesView:1',initialDivision||''),[tab,setTab]=useHistoryState('SeriesView:2','Tabell');if(!division)return <section><h2 style={{textAlign:'center'}}>Serier</h2><div className="series-directory"><div className="series-art"><img src="/series-portrait.png" alt="Orchisk Yaraaz-spelare, blyertsteckning"/></div><div className="series-groups">{['Kejsarserien','Division 1','Division 2','Division 3'].map((group,i)=><div key={group}><h3>{group}</h3>{DIVISION_NAMES.filter(n=>i===0?n===group:n.startsWith(group)).map((n,index)=><button style={{marginTop:i>=2&&index>0&&index%3===0?18:undefined}} className="text-link" key={n} onClick={()=>setDivision(n)}>{n}</button>)}</div>)}</div></div></section>;
 return <Division onClub={onClub} division={division} userClub={userClub} tab={tab} setTab={setTab} onBack={()=>setDivision('')} onSelect={(name:string)=>{setDivision(name);setTab('Tabell')}} onMatch={onMatch}/>;
}
function Division({division,userClub,tab,setTab,onBack,onMatch,onSelect,onClub}:any){const [forumOpen,setForumOpen]=useHistoryState('SeriesView:3',false),[season,setSeason]=useHistoryState('division-season','');const {data:seasons}=useData('/series/seasons');const {data:posts}=useData('/forum?category='+encodeURIComponent(division));const {data:clubs,error}=useData('/divisions/'+encodeURIComponent(division)+'/standings?season='+season),{data:fixtures}=useData('/fixtures?division='+encodeURIComponent(division)+'&season='+season);const sorted=[...clubs].sort((a,b)=>(b.wins*3+b.draws)-(a.wins*3+a.draws)||(b.goalsFor-b.goalsAgainst)-(a.goalsFor-a.goalsAgainst)||a.position-b.position);
 return <section><div className="page-title"><h2>{division}</h2><label>Säsong <select value={season} onChange={e=>setSeason(e.target.value)}><option value="">Aktuell säsong</option>{seasons.map((s:number)=><option key={s} value={s}>{s}</option>)}</select></label><button onClick={onBack}>Alla serier</button></div><div className="tabs">{['Tabell','Spelschema','Spelarstatistik','Divisionsträd','Spelade matcher'].map(t=><button role="tab" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><Message error={error}/>{tab==='Tabell'?<div className="division-columns"><div><table className="retro-table"><thead><tr>{['#','Lag','SM','V','O','F','PS','P'].map(h=><th key={h} title={h==='PS'?'Poängskillnad':h==='P'?'Seriepoäng':undefined}>{h}</th>)}</tr></thead><tbody>{sorted.map((c,i)=><tr key={c.id} className={(i===0?'promoted':i>=7?'relegated':'')+(c.id===userClub.id?' my-club':'')}><td>{i+1}</td><td><button className="text-link" onClick={()=>onClub(c.id)}><Crest race={c.race} small/>{c.name}</button></td><td>{c.wins+c.draws+c.losses}</td><td>{c.wins}</td><td>{c.draws}</td><td>{c.losses}</td><td>{c.goalsFor-c.goalsAgainst}</td><td>{c.wins*3+c.draws}</td></tr>)}</tbody></table><p className="compact">Plats 1: {division==='Kejsarserien'?'serievinnare':'direktuppflyttning'}.<br/>Plats 8–10: {division.startsWith('Division 3')?'lägsta serienivån':'nedflyttning'}.<br/>PS = poängskillnad, P = seriepoäng.</p><div className="notice"><h3>Senaste foruminlägget</h3><p>{posts[0]?<><button className="text-link" onClick={()=>setForumOpen(true)}>{posts[0].title||'Diskussion'}</button><br/>{posts[0].author} · {new Date(posts[0].lastDate).toLocaleDateString('sv-SE')}<br/>{posts[0].text?.slice(0,180)}</>:'Inga diskussioner ännu.'}</p><button onClick={()=>setForumOpen(true)}>Öppna serieforum</button></div></div><div><FixtureList fixtures={fixtures.filter(f=>f.played&&Array.from(new Set(fixtures.filter(x=>x.played).map(x=>x.round))).sort((a:any,b:any)=>b-a).slice(0,3).includes(f.round)).sort((a,b)=>b.round-a.round||a.id.localeCompare(b.id))} onMatch={onMatch}/></div></div>:tab==='Spelarstatistik'?<Statistics key={season} initialSeason={season||String(seasons[0]||1)} division={division} onOpen={e=>e.kind==='club'?onClub(e.id):window.dispatchEvent(new CustomEvent("arena-entity",{detail:e}))}/>:tab==='Divisionsträd'?<DivisionTree current={division} onSelect={onSelect}/>:<FixtureList fixtures={tab==='Spelade matcher'?fixtures.filter(f=>f.played):fixtures} onMatch={onMatch}/>} {forumOpen&&<Forum club={userClub} initialCategory={division} initialThread={posts[0]?.id||null} onClose={()=>setForumOpen(false)}/>}</section>;
}
export {Statistics} from './StatisticsPage';
