import {attributeBarPercent} from '../constants/attributes';
import {InjuryMark} from './InjuryMark';
import {RaceIcon} from './RaceIcon';
import {RACE_DISPLAY_NAMES} from '../constants/attributes';

import {useData} from './WorldViews';
import {useState} from 'react';import {Player} from '../types';import {ATTRIBUTE_NAMES_SV,getQualitativeLabel,getTotalInjuryLabel} from '../constants/attributes';import {Popup} from './Popup';
export function Meter({value}:{value:number}){return <span className="meter"><span>{getQualitativeLabel(value)}</span><span className="meter-track"><span className="meter-fill" style={{display:'block',width:attributeBarPercent(value)+'%'}}/></span></span>}
export function SquadOverview({players,onSelect,onClose}:{players:Player[];onSelect:(id:number)=>void;onClose:()=>void}){const {data:gains}=useData('/training-gains/'+(players[0]?.clubId||'none'));const raised=(id:number,k:string)=>gains.some((g:any)=>g.playerId===id&&g.attributes.includes(k));
 const [sort,setSort]=useState('shirtNumber'),[direction,setDirection]=useState(1);const attrs=Object.entries(ATTRIBUTE_NAMES_SV);const headers=[['shirtNumber','Nr'],['name','Namn'],['race','Ras'],...attrs,['wage','Lön'],['currentInjury','Skada'],['totalInjury','Total skada']];const value=(p:Player,k:string)=>(p.attributes as any)[k]??(p as any)[k];const rows=[...players].sort((a,b)=>{const x=value(a,sort),y=value(b,sort);return direction*(typeof x==='string'?x.localeCompare(y,'sv'):x-y)});
 return <Popup title="Spelaröversikt" wide onClose={onClose}><p>Klicka på en kolumnrubrik för stigande eller fallande sortering. Rött markerar ett passerat heltalssteg vid senaste veckoträningen.</p><table className="retro-table sort-grid"><thead><tr>{headers.map(([k,n])=><th key={k} aria-sort={sort===k?(direction===1?'ascending':'descending'):'none'}><button className="text-link" onClick={()=>{setSort(k);setDirection(sort===k?-direction:1)}}>{n}{sort===k?(direction===1?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td>{p.shirtNumber}</td><td><button className="text-link" onClick={()=>{onClose();onSelect(p.id)}}><RaceIcon race={p.race}/>{p.isDeceased?'✝ ':''}{p.name}</button></td><td>{RACE_DISPLAY_NAMES[p.race]}</td>{attrs.map(([k])=><td key={k} className={raised(p.id,k)?"training-raised":""} title={raised(p.id,k)?"Ökat ett helt steg vid senaste träningen":undefined}><Meter value={(p.attributes as any)[k]}/></td>)}<td>{p.wage}</td><td style={{color:'#a52620'}}>{<InjuryMark value={p.currentInjury}/>}</td><td>{getTotalInjuryLabel(p.totalInjury)}</td></tr>)}</tbody></table></Popup>}

